<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VuFindTheme\ResourceContainer'                 => __DIR__ . '/src/VuFindTheme/ResourceContainer.php',
    'VuFindTheme\View\Helper\InlineScript'          => __DIR__ . '/src/VuFindTheme/View/Helper/InlineScript.php',
    'VuFindTheme\View\Helper\MobileUrl'             => __DIR__ . '/src/VuFindTheme/View/Helper/MobileUrl.php',
    'VuFindTheme\View\Helper\HeadScript'            => __DIR__ . '/src/VuFindTheme/View/Helper/HeadScript.php',
    'VuFindTheme\View\Helper\HeadThemeResources'    => __DIR__ . '/src/VuFindTheme/View/Helper/HeadThemeResources.php',
    'VuFindTheme\View\Helper\HeadLink'              => __DIR__ . '/src/VuFindTheme/View/Helper/HeadLink.php',
    'VuFindTheme\View\Helper\ImageLink'             => __DIR__ . '/src/VuFindTheme/View/Helper/ImageLink.php',
    'VuFindTheme\View\Helper\Factory'               => __DIR__ . '/src/VuFindTheme/View/Helper/Factory.php',
    'VuFindTheme\InjectTemplateListener'            => __DIR__ . '/src/VuFindTheme/InjectTemplateListener.php',
    'VuFindTheme\Mobile'                            => __DIR__ . '/src/VuFindTheme/Mobile.php',
    'VuFindTheme\LessCompiler'                      => __DIR__ . '/src/VuFindTheme/LessCompiler.php',
    'VuFindTheme\Initializer'                       => __DIR__ . '/src/VuFindTheme/Initializer.php',
    'VuFindTheme\ThemeInfo'                         => __DIR__ . '/src/VuFindTheme/ThemeInfo.php',
    'VuFindTheme\Module'                            => __DIR__ . '/Module.php',
    'VuFindTest\ThemeResourceContainerTest'         => __DIR__ . '/tests/unit-tests/src/VuFindTest/ThemeResourceContainerTest.php',
    'VuFindTest\ThemeMobileTest'                    => __DIR__ . '/tests/unit-tests/src/VuFindTest/ThemeMobileTest.php',
    'VuFindTest\ThemeInfoTest'                      => __DIR__ . '/tests/unit-tests/src/VuFindTest/ThemeInfoTest.php',
    'VuFindTest\View\Helper\HeadThemeResourcesTest' => __DIR__ . '/tests/unit-tests/src/VuFindTest/View/Helper/HeadThemeResourcesTest.php',
    'VuFindTest\ThemeInjectTemplateListenerTest'    => __DIR__ . '/tests/unit-tests/src/VuFindTest/ThemeInjectTemplateListenerTest.php',
    'VuFindTest\LessCompilerTest'                   => __DIR__ . '/tests/unit-tests/src/VuFindTest/LessCompilerTest.php',
);
