<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = ($this->auth()->isLoggedIn()) ? $this->auth()->isLoggedIn()->getBookCart() : null;
  $cartId = $this->driver->getResourceSource() . '|' . $id;
?>
<ul class="nav nav-pills hidden-print">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <li><a id="save-record" class="modal-link <?=$controllerClass?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to List')?>"><i class="fa fa-plus"></i> <?=$this->transEsc('Add to List')?></a></li>
  <? endif; ?>
  <? if (!empty($addThis)): ?>
    <li><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <? endif; ?>
  <li id="bookbag-menu">
    <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
    <form class="form-inline" id="addToBookCart" method="post" name="bulkActionForm" action="/vufind/Cart/Home">
      <input type="checkbox" class="checkbox-select-item hidden" name="ids[]" value="<?=$cartId?>" checked />
      <input type="hidden" name="add" value="true" />
    </form>
    <a class="modal-link correct<? if($cart != null && $cart->contains($cartId)): ?> hidden<? endif ?> export-toggle" href="#" onclick="$('#addToBookCart').submit();"><i class="fa fa-plus"></i> <?=$this->transEsc('Add to Book Cart') ?></a>
    <form class="form-inline" id="deleteFromBookCart" method="post" name="bulkActionForm" action="/vufind/Cart/Home">
      <input type="checkbox" class="checkbox-select-item hidden" name="ids[]" value="<?=$cartId?>" checked />
      <input type="hidden" name="delete" value="true" />
    </form>
    <a class="modal-link correct<? if($cart == null || !$cart->contains($cartId)): ?> hidden<? endif ?> export-toggle" href="#" onclick="$('#deleteFromBookCart').submit();"><i class="fa fa-minus-circle"></i> <?=$this->transEsc('Remove from Book Cart') ?></a>
    <noscript>
      <form method="post" name="addForm" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>">
        <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
        <? if ($cart != null && !$cart->contains($cartId)): ?>
          <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Cart')?>"/>
        <? else: ?>
          <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Cart')?>"/>
        <? endif; ?>
      </form>
    </noscript>
  </li>
</ul>
