<? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <? $caption = ""; 
     foreach ($list as $sortType => $sortData): 
       if($sortData['selected']):
         $caption = $this->transEsc($sortData['desc']);
       endif;
     endforeach; ?>
  <div class="EIN-col-m-4" style="display:inline;float:none;white-space:nowrap">
    <button class="btn-alternate" id="sortButton" data-toggle="dropdown" data-target="#sortButtonDropdown"><?=$caption?><i class="fa fa-caret-down"></i></button>
    <div class="EIN-col-m-12 dropdown" id="sortButtonDropdown">
      <ul role="navigation" class="dropdown-menu standardDropdown">
        <? foreach ($list as $sortType => $sortData): ?>
          <li><button class="btn-dropdown btn-standardDropdown manageListDropdown" onclick="submitSortForm('<?=$this->escapeHtmlAttr($sortType)?>')"><?=$this->transEsc($sortData['desc'])?></button></li>
        <? endforeach; ?>
      </ul>
    </div>
  </div>
  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort">
    <input type="hidden" id="sort_options_1" name="sort">
    <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
  <script type="text/javascript">
    function submitSortForm(sortType) {
      $('#sort_options_1').val(sortType);
      $("form[name='sort']").submit();
    }

    jQuery(document).ready(function() {
      test = setTimeout(function() {
        $('#sortButton').css("width", $('#sortButtonDropdown').children().outerWidth());
      }, 50);
    });
  </script>
<? endif; ?>
