<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VuFindDevTools\Controller\DevtoolsController' => __DIR__ . '/src/VuFindDevTools/Controller/DevtoolsController.php',
    'VuFindDevTools\Module'                        => __DIR__ . '/Module.php',
    'VuFindTest\Controller\DevtoolsControllerTest' => __DIR__ . '/tests/unit-tests/src/VuFindTest/Controller/DevtoolsControllerTest.php',
);
