<?
  // Set up page title:
  $this->headTitle($this->translate('Checked Out'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();

  $order = ['overdue','due_this_week','other'];
  $totalCheckouts = 0;
?>

<?=($this->suppressFlashMessages) ? "" : $this->flashmessages()?>

<div class="EIN-col-m-12 padded">
  <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
    <div class="facetTitle">Checked Out</div>
    <? foreach($order as $checkoutType): ?>
      <? $totalCheckouts += count($this->checkoutList[$checkoutType]); ?>
      <div class="panel-heading">
        <h4 class="panel-title">
          <? if(count($this->checkoutList[$checkoutType]) > 0): ?>    
            <a data-toggle="collapse" data-parent="#checkoutAccordion" href="#details_<?=$checkoutType?>" class="collapsed active"><?=$this->transEsc('checkedout_' . $checkoutType)?><span class="badge noHide"><?=count($this->checkoutList[$checkoutType])?></span></a>
          <? else: ?>
            <a data-toggle="collapse" class="collapsed disabled" onclick="return false;"><?=$this->transEsc('checkedout_' . $checkoutType)?><span class="badge noHide"><?=count($this->checkoutList[$checkoutType])?></span></a>
          <? endif; ?>
          <div class="openAccordionTab"></div>
        </h4>
      </div>
    <? endforeach; ?>
    <div class="panel-heading"></div>
  </div> 
  <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9 panel-group" id="checkoutAccordion">
    <h1 class="pageTitle EIN-hide-t EIN-hide">Checked Out</h1>
    <? if( $totalCheckouts == 0 ): ?>
      <div class="EIN-col-m-12" style="height:110px"></div>
      <div class="center">You don't currently have any items checked out.</div>
      <div class="EIN-col-m-12" style="height:110px"></div>
    <? else: ?>
      <? foreach($order as $checkoutType): ?>
        <div class="panel panel-default listAccordion">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <? if(count($this->checkoutList[$checkoutType]) > 0): ?>    
                <a data-toggle="collapse" data-parent="#checkoutAccordion" href="#details_<?=$checkoutType?>" class="collapsed active"><?=$this->transEsc('checkedout_' . $checkoutType)?><span class="badge noHide"><?=count($this->checkoutList[$checkoutType])?></span><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
              <? else: ?>
                <a data-toggle="collapse" class="collapsed disabled"><?=$this->transEsc('checkedout_' . $checkoutType)?><span class="badge noHide"><?=count($this->checkoutList[$checkoutType])?></span><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
              <? endif; ?>
            </h4>
          </div>
          <? if(count($this->checkoutList[$checkoutType]) > 0): ?>    
            <div id="details_<?=$checkoutType?>" class="panel-collapse collapse">
              <div class="panel-body">
                <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>">
                  <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', array('idPrefix' => '', 'checkout' => $checkoutType, 'account' => $this->account))?>
                  <div style="display:none">
                    <? foreach ($this->checkoutList[$checkoutType] as $current): ?>
                      <? if (isset($current["checkout_id"])): ?>
                        <?=$this->record($current["driver"])->getHoldCheckbox($current["checkout_id"])?>
                      <? endif; ?>
                    <? endforeach; ?>
                  </div>
                </form>
                <? foreach ($this->checkoutList[$checkoutType] as $current): ?>
                  <?=$this->record($current["driver"])->getCheckoutEntry($current, $user)?>
                <? endforeach; ?>
              </div>
            </div>
          <? endif; ?>
        </div>
      <? endforeach; ?>
      <script type="text/javascript">
        $('.panel-heading a').on('click',function(e){
          // prevent them from dismissing the last open section if we're in tablet or desktop layout
          if($(document).width() >= 600) {
            if($($(this).attr("href")).hasClass('in')){
              e.stopPropagation();
            }
            // You can also add preventDefault to remove the anchor behavior that makes the page jump
            e.preventDefault();
          }
        });
        jQuery(document).ready(function() {
          $('body').css({"overflow-y":"hidden"});
          if($(document).width() >= <?=(isset($this->showCheckoutType) ? 0 : 600)?>) {
            <? if( isset($this->showCheckoutType) ): ?>
              $('#details_<?=$this->showCheckoutType?>').parents('.listAccordion').find('.panel-heading a').click();
            <? else: ?>
              $('.panel-heading a.active').first().click();
            <? endif; ?>
          }
          $('body').css({"overflow-y":"auto"});
          $('#detailsAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});
        } );
      </script>
    <? endif; ?>
  </div>
</div>
