<p class="lead lightbox-header" style="display:none"><?=$this->transEsc('Filter Results')?></p>
<div id="facetsModalDiv">
</div>
<div class="modal-footer">
  <button class="btn-alternate btn-wide" onclick="$('#modalClose').click()">Cancel</button>
  <a href="" id="facetSubmitLink"><button class="btn-default btn-wide">Apply</button></a>
</div>
<script type="text/javascript">  
$(document).ready( function() { 
  var facetsContent = "";
  Lightbox.addOpenAction( function openFunc() { 
    facetsContent = $('#facetsDiv').html();
    if( facetsContent != "" ) {
      $('#facetsDiv').html("");
      $('#facetsModalDiv').html(facetsContent);
      setTimeout(sizeModal, 100 );
    }
    // remove this function from the open stack, since it doesn't clean up after itself automatically like close actions do
    Lightbox.openStack.splice(Lightbox.openStack.indexOf(openFunc), 1);
  } );

  Lightbox.addCloseAction( function() {
    if( facetsContent != "" ) {
      $('#facetsDiv').html(facetsContent);
      facetsContent = "";
    }
  } );
} );
</script>
