<?
  // Set up page title:
  $this->headTitle($this->translate('Holds'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Holds') . '</li>';

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();

  $order = ['ready','transit','hold','frozen'];
  $totalHolds = 0;
?>

<?=($this->suppressFlashMessages) ? "" : $this->flashmessages()?>

<div class="EIN-col-m-12 padded">
  <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
    <div class="facetTitle">Holds</div>
    <? foreach($order as $holdType): ?>
      <? $totalHolds += count($this->holdList[$holdType]); ?>
      <? if(count($this->holdList[$holdType]) > 0): ?>    
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#holdAccordion" href="#details_<?=$holdType?>" class="collapsed"<? /** ?> onclick="setTimeout( function() { $('#sortButton<?=$list->id?>').css('width', $('#sortButtonDropdown<?=$list->id?>').children().outerWidth())}, 10);"<? /**/ ?>><?=$this->transEsc('holdtype_' . $holdType)?><span class="badge noHide"><?=count($this->holdList[$holdType])?></span></a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
      <? endif; ?>
    <? endforeach; ?>
    <div class="panel-heading"></div>
  </div> 
  <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9 panel-group" id="holdAccordion">
    <h1 class="pageTitle EIN-hide-t EIN-hide">Holds</h1>
    <? if( $totalHolds == 0 ): ?>
      <div class="EIN-col-m-12" style="height:50px"></div>
      <div class="center">You don't currently have any holds.</div>
      <div class="EIN-col-m-12" style="height:50px"></div>
    <? else: ?>
      <? foreach($order as $holdType): ?>
        <? if(count($this->holdList[$holdType]) > 0): ?>    
          <div class="panel panel-default listAccordion">
            <div class="panel-heading EIN-hide-t EIN-hide">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#holdAccordion" href="#details_<?=$holdType?>" class="collapsed"<? /** ?> onclick="setTimeout( function() { $('#sortButton<?=$list->id?>').css('width', $('#sortButtonDropdown<?=$list->id?>').children().outerWidth())}, 10);"<? /**/ ?>><?=$this->transEsc('holdtype_' . $holdType)?><span class="badge noHide"><?=count($this->holdList[$holdType])?></span><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
              </h4>
            </div>
            <div id="details_<?=$holdType?>" class="panel-collapse collapse">
              <div class="panel-body">
                <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>">
                  <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', array('idPrefix' => '', 'hold' => $holdType, 'account' => $this->account))?>
                  <div style="display:none">
                    <? foreach ($this->holdList[$holdType] as $current): ?>
                      <?=$this->record($current["driver"])->getHoldCheckbox($current["hold_id"])?>
                    <? endforeach; ?>
                  </div>
                </form>
                <? foreach ($this->holdList[$holdType] as $current): ?>
                  <?=$this->record($current["driver"])->getHoldEntry($current)?>
                <? endforeach; ?>
              </div>
            </div>
          </div>
        <? endif; ?>
      <? endforeach; ?>
      <script type="text/javascript">
        $('.panel-heading a').on('click',function(e){
          // prevent them from dismissing the last open section if we're in tablet or desktop layout
          if($(document).width() >= 600) {
            if($($(this).attr("href")).hasClass('in')){
              e.stopPropagation();
            }
            // You can also add preventDefault to remove the anchor behavior that makes the page jump
            e.preventDefault();
          }
      });
      $('body').css({"overflow-y":"hidden"});
        if($(document).width() >= <?=(isset($this->showHoldType) ? 0 : 600)?>) {
          <? if( isset($this->showHoldType) ): ?>
            $('#details_<?=$this->showHoldType?>').parents('.listAccordion').find('.panel-heading a').click();
          <? else: ?>
            $('.panel-heading a').first().click();
          <? endif; ?>
        }
        $('body').css({"overflow-y":"auto"});
        $('#detailsAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});
      </script>
    <? endif; ?>
  </div>
</div>
