<?
  // Set up page title:
  $this->headTitle($this->translate('Logout Warning'));
?>

<p class="lead lightbox-header" style="display:none"><?=$this->transEsc('Logout Warning')?></p>
<div>
  <div class="EIN-col-m-12" style="font-weight:700;font-size:18px">Attention:</div>
  <div class="EIN-col-m-12" style="font-size:18px">Your catalog session is about to expire if you don't click the Continue button.</div>
</div>
<div class="modal-footer">
  <button class="btn-default btn-wide" onclick="autoLogoutResetTimer(); $('#modalClose').click();">Continue</button>
  <a href="/MyResearch/Logout?target=home"><button class="btn-alternate btn-wide">Exit</button></a>
</div>