<?
  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->isLoggedIn();
  $isBookCart = (count($this->results) == 1) && ($this->results[0]["list"]->title == "Book Cart");

  // Set up page title:
  $this->headTitle($isBookCart ? $this->results[0]["list"]->title : $this->translate('Lists'));

  // Set up breadcrumbs:
  $currPage = $isBookCart ? 'List' : 'Favorites';
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc($currPage) . '</li>';

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile("check_item_statuses.js");
?>

<?=$this->flashmessages()?>

<div class="EIN-col-m-12 padded">
  <? if( count($this->results) > 0 && !$isBookCart ): ?>
    <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
      <div class="facetTitle">Lists</div>
      <? foreach($this->results as $thisResult): ?>
        <? $list = $thisResult["list"]; ?>    
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#listAccordion" href="#details<?=$list->id?>" class="collapsed" onclick="setTimeout( function() { $('#sortButton<?=$list->id?>').css('width', $('#sortButtonDropdown<?=$list->id?>').children().outerWidth())}, 10);"><?=$list->title?><span class="badge"><?=$thisResult["items"]->getResultTotal()?></span></a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
      <? endforeach; ?>
      <div class="panel-heading">
        <h4 class="panel-title">
          <a onclick="Lightbox.get('MyResearch','editList',{'id':'NEW'})" class="collapsed">Create New List</a>
          <div class="openAccordionTab"></div>
        </h4>
      </div>
      <div class="panel-heading"></div>
    </div>
    <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9">
      <h1 class="pageTitle EIN-hide-t EIN-hide"><?=($isBookCart ? ($this->results[0]["list"]->title) : "Lists")?></h1>
  <? else: ?>
    <div class="EIN-col-m-12">
      <h1 class="pageTitle"><?=($isBookCart ? ($this->results[0]["list"]->title) : "Lists")?></h1>
  <? endif; ?>
    <? if( count($this->results) == 0 ): ?>
      <div class="EIN-col-m-12" style="height:20px"></div>
      <div class="center">You have not created any lists yet.</div>
    <? else: ?>
      <? if( !$isBookCart ): ?>
        <div class="panel-group" id="listAccordion">
      <? endif; ?>
      <? foreach($this->results as $thisResult): ?>
        <? $list = $thisResult["list"]; ?>
        <? if( !$isBookCart ): ?>
          <div class="panel panel-default listAccordion">
            <div class="panel-heading EIN-hide-t EIN-hide">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#listAccordion" href="#details<?=$list->id?>" class="collapsed" onclick="setTimeout( function() { $('#sortButton<?=$list->id?>').css('width', $('#sortButtonDropdown<?=$list->id?>').children().outerWidth())}, 10);"><?=$list->title?><span class="badge"><?=$thisResult["items"]->getResultTotal()?></span><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
              </h4>
            </div>
            <div id="details<?=$list->id?>" class="panel-collapse collapse">
        <? endif; ?>
        <div class="panel-body">
          <? if ($list && !empty($list->description)): ?>
            <p><?=$this->escapeHtml($list->description)?></p>
          <? endif; ?>
          <? if ($thisResult["items"]->getResultTotal() > 0): ?>
            <div class="clearfix hidden-print center">
              <div class="EIN-hide-m EIN-col-t-12 EIN-col-12" style="height:10px"></div>
              <table style="margin:auto;display:inline-block">
                <tr>
                  <td><span><strong><?=$this->localizedNumber($thisResult["items"]->getResultTotal())?></strong> titles sorted by </span></td>
                  <td style="padding-left:5px"><?=$this->render('search/controls/sort.phtml', ['params' => $thisResult["items"]->getParams(), 'results' => $thisResult["items"], 'id' => $thisResult["list"]->id, 'list' => $list->id])?></td>
                </tr>
              </table>
            </div>
          <? endif; ?>
          <? if ($thisResult["items"]->getResultTotal() > 0): ?>
            <form class="form-inline" method="post" action="<?=$this->url('cart-myresearchbulk')?>" target="loginFrame">
              <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', array('idPrefix' => '', 'list' => isset($list) ? $list : null, 'account' => $this->account))?>
              <div style="display:none">
                <? foreach ($thisResult["items"]->getResults() as $i=>$current): ?>
                  <?=$this->record($current)->getCheckbox()?>
                <? endforeach; ?>
              </div>
            </form>
            <? foreach ($thisResult["items"]->getResults() as $i=>$current): ?>
              <?=$this->record($current)->getListEntry($list, $user)?>
            <? endforeach; ?>
          <? else: ?>
            <p><?=$this->transEsc('You do not have any saved resources' . ($list->isBookCart() ? " BOOKCART" : ""))?></p>
          <? endif; ?>
          <? if (isset($list) && !($list->isBookCart())): ?>
            <? if ($list->editAllowed($account->isLoggedIn())): ?>
              <div class="EIN-col-m-12 center">Edit List:
                <button class="btn-alternate btn-wide EIN-hide-m" onclick="Lightbox.get('MyResearch', 'EditList', {'id':'<?=$list->id?>'})"><i class="fa fa-pencil"></i><?=$this->transEsc("edit_list")?></button></td>
                <button class="btn-alternate btn-wide EIN-hide-m" onclick="Lightbox.get('MyResearch', 'DeleteList', {'id':'<?=$list->id?>'})"><i class="fa fa-trash"></i><?=$this->transEsc("delete_list")?></button></td>
              </div>
              <div class="EIN-col-m-6 EIN-hide-t EIN-hide">
                <button class="btn-alternate leftButton" onclick="Lightbox.get('MyResearch', 'EditList', {'id':'<?=$list->id?>'})"><i class="fa fa-pencil"></i><?=$this->transEsc("edit_list")?></button></td>
              </div>
              <div class="EIN-col-m-6 EIN-hide-t EIN-hide">
                <button class="btn-alternate rightButton" onclick="Lightbox.get('MyResearch', 'DeleteList', {'id':'<?=$list->id?>'})"><i class="fa fa-trash"></i><?=$this->transEsc("delete_list")?></button></td>
              </div>
            <? endif; ?>
          <? endif; ?>
        </div>
        <? if( !$isBookCart ): ?>
            </div>
          </div>
        <? endif; ?>
      <? endforeach; ?>
      <? if( !$isBookCart ): ?>
        <script type="text/javascript">
          $('.panel-heading a').on('click',function(e){
            // prevent them from dismissing the last open section if we're in tablet or desktop layout
            if($(document).width() >= 600) {
              if($($(this).attr("href")).hasClass('in')){
                e.stopPropagation();
              }
              // You can also add preventDefault to remove the anchor behavior that makes the page jump
              e.preventDefault();
            }
          });
          jQuery(document).ready(function() {
            $('body').css({"overflow-y":"hidden"});
            if($(document).width() >= <?=(isset($this->showList) ? 0 : 600)?>) {
              <? if( isset($this->showList) ): ?>
                $('input[name="listID"][value="<?=$this->showList?>"]').parents('.listAccordion').find('.panel-heading a').click();
              <? else: ?>
                $('.panel-heading a').first().click();
              <? endif; ?>
            }
            $('body').css({"overflow-y":"auto"});
            $('#detailsAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});
            // if they switch from mobile to tablet/desktop, make sure there's an open tab
            $(window).resize( function() { 
              if(($(document).width() >= 600) && ($('#listAccordion').find('div .collapse.in').length == 0) ) {
                $('.panel-heading a').first().click();
              }
            });
          } );
        </script>
      <? endif; ?>
    <? endif; ?>
    <? if( $isBookCart ): ?>
      <div class="EIN-col-m-12 EIN-hide-t EIN-hide" style="height:10px"></div>
    <? elseif( count($this->results) == 0 ): ?>
      <div class="EIN-col-m-12" style="height:20px"></div>
      <div class="EIN-col-m-12 center">
        <button class="btn-default btn-wide" onclick="Lightbox.get('MyResearch','editList',{'id':'NEW'})">Create New List</button>
      </div>
      <div class="EIN-col-m-12" style="height:10px"></div>
    <? else: ?>
      <div class="EIN-col-m-12 EIN-hide-t EIN-hide center">
        <div class="EIN-col-m-12" style="height:20px"></div>
        <button class="btn-default btn-wide" onclick="Lightbox.get('MyResearch','editList',{'id':'NEW'})">Create New List</button>
        <div class="EIN-col-m-12" style="height:10px"></div>
      </div>
    <? endif; ?>
  </div>
</div>
