<h1 class="pageTitle">Message Center</h1>
<div class="EIN-col-m-12 padded">
  <? if( count($this->notifications) == 0 ): ?>
    <div class="EIN-col-m-12" style="height:50px"></div>
    <div class="EIN-col-m-12 center">You currently have no messages.</div>
    <div class="EIN-col-m-12" style="height:50px"></div>
  <? else: ?>
    <table class="EIN-col-m-12">
      <tr><td class="bold">Click a subject line below to read the message</td></tr>
      <? foreach($this->notifications as $thisMessage): ?>
        <tr><td>
          <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
          <div class="EIN-col-m-12 messageRow" onclick="Lightbox.get('MyResearch','Notifications',false,{'showMessage':true,'subject':'<?=$this->transEsc($thisMessage["subject"])?>','message':'<?=$this->transEsc($thisMessage["message"])?>'})"><?=$thisMessage["subject"] . (isset($thisMessage["extra"]) ? $thisMessage["extra"] : "")?></div>
        </td></tr>
      <? endforeach; ?>
    </table>
  <? endif; ?>
  <div class="EIN-col-m-12" style="height:10px"></div>
</div>