    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-noBorderAlternate close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i></button>
          <h4 class="modal-title">Pickup Location</h4>
        </div>
        <div class="modal-body" style="text-align:center">
          <form method="post" name="placeHold">
            <h5 class="modalSubheading">Preferred</h5>
            <h5 class="modalSubheading">Others</h5>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn-default">Okay</button>
        </div>
      </div>
    </div>
