<?
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Only display home library form if we have multiple pickup locations:
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<?=($this->suppressFlashMessages) ? "" : $this->flashmessages()?>

<div class="EIN-col-m-12 padded">
  <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
    <div class="facetTitle">Profile</div>
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_aboutMe" class="collapsed"><?=$this->transEsc('profile_aboutMe')?></a>
        <div class="openAccordionTab"></div>
      </h4>
    </div>
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_card" class="collapsed"><?=$this->transEsc('profile_card')?></a>
        <div class="openAccordionTab"></div>
      </h4>
    </div>
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_security" class="collapsed"><?=$this->transEsc('profile_security')?></a>
        <div class="openAccordionTab"></div>
      </h4>
    </div>
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_libraries" class="collapsed"><?=$this->transEsc('profile_libraries')?></a>
        <div class="openAccordionTab"></div>
      </h4>
    </div>
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_overdrive" class="collapsed"><?=$this->transEsc('profile_overdrive')?></a>
        <div class="openAccordionTab"></div>
      </h4>
    </div>
    <div class="panel-heading"></div>
  </div> 
  <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9 panel-group" id="profileAccordion">
    <h1 class="pageTitle EIN-hide-t EIN-hide">Profile</h1>
    <div class="panel panel-default listAccordion">
      <div class="panel-heading EIN-hide-t EIN-hide">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_aboutMe" class="collapsed"><?=$this->transEsc('profile_aboutMe')?><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
        </h4>
      </div>
      <div id="profile_aboutMe" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="EIN-col-m-12" style="height:5px"></div>
          <form class="form-inline" method="post" action="<?=$this->url('myresearch-profile')?>" target="loginFrame">
            <input type="hidden" name="profileSection" value="aboutMe" />
            <input type="hidden" name="suppressFlashMessages" value="true" />
            <input type="hidden" name="reloadParent" value="true" />
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Name</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue"><?=$this->profile["firstname"] . " " . $this->profile["lastname"]?></div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Address</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue"><?=$this->profile["address1"]?></div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Email</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue clickable" onclick="Lightbox.get('Confirm', 'EditProperty', {'data':{'path':'myresearch-profile','referringSection':'aboutMe','property':'Email','propertyName':'email','currentValue':'<?=$this->profile["email"]?>'}})"><?=$this->profile["email"]?><i class="fa fa-pencil floatR"></i></div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Phone Number</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue clickable" onclick="Lightbox.get('Confirm', 'EditProperty', {'data':{'path':'myresearch-profile','referringSection':'aboutMe','property':'Phone Number','propertyName':'phone','currentValue':'<?=$this->profile["phone"]?>'}})"><?=$this->profile["phone"]?><i class="fa fa-pencil floatR"></i></div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Notification Preference</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue">
              <?
                $selected = (isset($this->profile['notificationCode']) && $this->profile['notificationCode'] != "") ? $this->profile['notificationCode'] : '';
              ?>
              <select id="notification" name="notification" class="form-control registerDropdown" onchange="$(this).parents('form').submit();" disabled>
                <option value="z"<?=($selected == "Email")?' selected="selected"':''?>>Email</option>
                <option value="p"<?=($selected == "Phone")?' selected="selected"':''?>>Phone</option>
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="panel panel-default listAccordion">
      <div class="panel-heading EIN-hide-t EIN-hide">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_card" class="collapsed"><?=$this->transEsc('profile_card')?><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
        </h4>
      </div>
      <div id="profile_card" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="EIN-col-m-12" style="height:5px"></div>
          <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Number</div>
          <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue"><?=$this->profile["cat_username"]?></div>
          <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
          <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Expiration</div>
          <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue"><?=$this->profile["expiration"]?></div>
        </div>
      </div>
    </div>
    <div class="panel panel-default listAccordion">
      <div class="panel-heading EIN-hide-t EIN-hide">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_security" class="collapsed"><?=$this->transEsc('profile_security')?><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
        </h4>
      </div>
      <div id="profile_security" class="panel-collapse collapse">
        <div class="panel-body" style="text-align:center">
          <div class="EIN-col-m-12" style="height:5px"></div>
          <div class="EIN-hide-m EIN-col-t-12 EIN-col-12" style="height:20px"></div>
          <button class="btn-default btnWide" onclick="Lightbox.get('Confirm', 'EditProperty', {'data':{'path':'myresearch-profile','referringSection':'security','property':'PIN','propertyName':'pin','currentValue':'<?=hash_hmac("sha256", $this->profile["cat_password"], "eiNetwork")?>','barcode':'<?=$this->profile["cat_username"]?>'}})">Change PIN</button>
        </div>
      </div>
    </div>
    <div class="panel panel-default listAccordion">
      <div class="panel-heading EIN-hide-t EIN-hide">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_libraries" class="collapsed"><?=$this->transEsc('profile_libraries')?><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
        </h4>
      </div>
      <div id="profile_libraries" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="EIN-col-m-12" style="height:5px"></div>
          <form class="form-inline" method="post" action="<?=$this->url('myresearch-profile')?>" target="loginFrame">
            <input type="hidden" name="profileSection" value="libraries" />
            <input type="hidden" name="suppressFlashMessages" value="true" />
            <input type="hidden" name="reloadParent" value="true" />
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Preferred Library</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
              <? $selected = (isset($this->profile['preferredlibrarycode']) && $this->profile['preferredlibrarycode'] != "") ? $this->profile['preferredlibrarycode'] : $this->defaultPickupLocation ?>
              <select id="preferred_library" name="preferred_library" class="form-control registerDropdown" onchange="$(this).parents('form').submit();">
                <? foreach ($this->pickup as $lib): ?>
                  <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->escapeHtml($lib['locationDisplay'])?></option>
                <? endforeach; ?>
              </select>
            </div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Alternate Library</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
              <? $selected = (isset($this->profile['alternatelibrarycode']) && $this->profile['alternatelibrarycode'] != "") ? $this->profile['alternatelibrarycode'] : $this->defaultPickupLocation ?>
              <select id="alternate_library" name="alternate_library" class="form-control registerDropdown" onchange="$(this).parents('form').submit();">
                <? foreach ($this->pickup as $lib): ?>
                  <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->escapeHtml($lib['locationDisplay'])?></option>
                <? endforeach; ?>
              </select>
            </div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle">Home Library</div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8 fieldValue"><?=$this->profile["homelibrary"]?></div>
          </form>
        </div>
      </div>
    </div>
    <div class="panel panel-default listAccordion">
      <div class="panel-heading EIN-hide-t EIN-hide">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#profileAccordion" href="#profile_overdrive" class="collapsed"><?=$this->transEsc('profile_overdrive')?><i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
        </h4>
      </div>
      <div id="profile_overdrive" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="EIN-col-m-12" style="height:5px"></div>
          <form class="form-inline" method="post" action="<?=$this->url('myresearch-profile')?>" target="loginFrame">
            <input type="hidden" name="profileSection" value="overdrive" />
            <input type="hidden" name="suppressFlashMessages" value="true" />
            <input type="hidden" name="reloadParent" value="true" />
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle"><?=$this->transEsc('eBook')?></div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
              <? $selected = (isset($this->profile['OD_eBook']) && $this->profile['OD_eBook'] != "") ? explode(" ", $this->profile['OD_eBook'])[0] : null; ?>
              <select id="OD_eBook" name="OD_eBook" class="form-control registerDropdown" onchange="$(this).parents('form').submit();">
                <? foreach ($this->profile['OD_renewalInDays']['eBook'] as $renewOption): ?>
                  <option value="<?=$this->escapeHtmlAttr($renewOption)?>"<?=($selected == $renewOption)?' selected="selected"':''?>><?=$this->escapeHtml($renewOption)?> days</option>
                <? endforeach; ?>
              </select>
            </div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle"><?=$this->transEsc('Audiobook')?></div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
              <? $selected = (isset($this->profile['OD_audiobook']) && $this->profile['OD_audiobook'] != "") ? explode(" ", $this->profile['OD_audiobook'])[0] : null; ?>
              <select id="OD_audiobook" name="OD_audiobook" class="form-control registerDropdown" onchange="$(this).parents('form').submit();">
                <? foreach ($this->profile['OD_renewalInDays']['Audiobook'] as $renewOption): ?>
                  <option value="<?=$this->escapeHtmlAttr($renewOption)?>"<?=($selected == $renewOption)?' selected="selected"':''?>><?=$this->escapeHtml($renewOption)?> days</option>
                <? endforeach; ?>
              </select>
            </div>
            <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
            <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4 fieldTitle"><?=$this->transEsc('Video')?></div>
            <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
              <? $selected = (isset($this->profile['OD_video']) && $this->profile['OD_video'] != "") ? explode(" ", $this->profile['OD_video'])[0] : null; ?>
              <select id="OD_video" name="OD_video" class="form-control registerDropdown" onchange="$(this).parents('form').submit();">
                <? foreach ($this->profile['OD_renewalInDays']['Video'] as $renewOption): ?>
                  <option value="<?=$this->escapeHtmlAttr($renewOption)?>"<?=($selected == $renewOption)?' selected="selected"':''?>><?=$this->escapeHtml($renewOption)?> days</option>
                <? endforeach; ?>
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      $('.panel-heading a').on('click',function(e){
        // prevent them from dismissing the last open section if we're in tablet or desktop layout
        if($(document).width() >= 600) {
          if($($(this).attr("href")).hasClass('in')){
            e.stopPropagation();
          }
          // You can also add preventDefault to remove the anchor behavior that makes the page jump
          e.preventDefault();
        }
      });
      $('body').css({"overflow-y":"hidden"});
      if($(document).width() >= <?=(isset($this->showProfileSection) ? 0 : 600)?>) {
        <? if( isset($this->showProfileSection) ): ?>
          $('#profile_<?=$this->showProfileSection?>').parents('.listAccordion').find('.panel-heading a').click();
        <? else: ?>
          $('.panel-heading a').first().click();
        <? endif; ?>
      }
      $('body').css({"overflow-y":"auto"});
      $('#profileAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});
      <? if( isset($this->reloadParent) && $this->reloadParent ): ?>
        parent.location.reload();
      <? endif; ?>
    </script>
  </div>
</div>
