<div class="EIN-col-m-12">
  <span>eiNetwork editable text before the Quipu form.</span>
</div>

<div id="eCARDFiles">
  <link href="https://ecard.quipugroup.net/css/eCARD.css" rel="stylesheet">
  <link href="https://ecard.quipugroup.net/js/jqueryUI/css/ui-lightness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet">
  <script type="text/javascript" src="https://ecard.quipugroup.net/js/jquery-1.11.1.min.js"></script>
  <script type="text/javascript" src="https://ecard.quipugroup.net/js/jqueryUI/js/jquery-ui-1.10.4.custom.min.js"></script>
  <script type="text/javascript" src="https://ecard.quipugroup.net/js/jquery.xdomainrequest.min.js"></script>
  <script type="text/javascript" src="https://ecard.quipugroup.net/js/jquery.PrintArea.js"></script>
  <script type="text/javascript" src="https://ecard.quipugroup.net/js/eCARDMain.js"></script>
  <script type="text/javascript" src="https://ecard.quipugroup.net/Libraries/35/eCARDLibrary.js"></script>
</div>

<div id="eCARD" data-language="en" data-branchid="">
  <!-- eCARD requires JavaScript in order to display the registration form -->
  <!-- The following will detect if JavaScript is enabled on the patron's browser -->
  <noscript>
    <h2 style="color:red;">Warning - JavaScript Required</h2>
    <p>For full functionality of this web page it is necessary to enable JavaScript in your browser. For more information on most browsers, try <a href="http://www.enable-javascript.com/" target="_blank">How to enable JavaScript</a> OR <a href="http://activatejavascript.org/en/instructions" target="_blank">activatejavascript.org</a><</p>
  </noscript>
</div>

<div class="EIN-col-m-12">
  <span>eiNetwork editable text after the Quipu form.</span>
</div>
