<button id="loginModalLogin" class="btn-alternate btn-wide active" onmouseover="HighlightLoginModal(this.id, true)" onmouseout="HighlightLoginModal(this.id, false)" onclick="ToggleLoginModal(this);">Log In</button>
<button id="loginModalRegister" class="btn-alternate btn-wide" onmouseover="HighlightLoginModal(this.id, true)" onmouseout="HighlightLoginModal(this.id, false)" onclick="ToggleLoginModal(this);">Register</button><br><br>
<div id="loginModalLoginBody">
  <form role="login" method="post" action="<?=$this->url('myresearch-home')?>" name="loginForm" id="loginForm" autocomplete="off" target="loginFrame">
    <? $account = $this->auth()->getManager(); ?>
    <div class="textBoxContainer">
      <input type="text" name="username" id="login_username" value="Enter your Barcode" onfocus="ClearFormError(this); if (this.value=='Enter your Barcode') {this.value = '';this.style.color='#3d3d3d';}" class="form-control textBox"/>
      <i class="fa fa-exclamation-circle formErrorIcon"></i>
      <span id="login_usernameError" class="formError"></span>
    </div><br>
    <div class="textBoxContainer">
      <input type="text" name="password" id="login_password" value="Enter your PIN" onfocus="ClearFormError(this); if (this.value=='Enter your PIN') { this.value = ''; this.type='password'; this.style.color='#3d3d3d';}" class="form-control textBox"/>
      <i class="fa fa-exclamation-circle formErrorIcon"></i>
      <span id="login_passwordError" class="formError"></span>
    </div>
    <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
    <input type="hidden" name="authorization_code" id="authorization_code" value="">
    <input type="hidden" name="authorization_code" id="authorization_code" value="">
  </form>
</div>
<div id="loginModalRegisterBody" style="color:#3f51b5;display:none">REGISTER</div>
<div class="modal-footer">
  <div id="loginModalLoginFooter">
    <button class="btn-alternate btn-wide" aria-hidden="true" onclick="$('#modalClose').click()">Cancel</button>
    <button class="btn-default btn-wide" onclick="SubmitLogIn()">Log In</button>
  </div>
  <div id="loginModalRegisterFooter" style="display:none">
    <button class="btn-alternate btn-wide" aria-hidden="true" onclick="$('#modalClose').click()">Cancel</button>
    <button class="btn-default btn-wide" onclick="document.getElementById('loginForm').submit()">Register</button>
  </div>
  <div id="loadingFooter" style="display:none;padding:9px;color:#3d3d3d">
    <span><i class="fa fa-spinner"></i></span>
    <span>&nbsp;Loading...</span>
  </div
</div>

<script type="text/javascript">
  // the form starts displaying the login screen
  var loginToggle = "loginModalLogin";
  var processingLogin = false;
  // flip the modal to the desired function (log in OR register)
  function ToggleLoginModal(target) {
    // can't do anything while we're processing
    if( processingLogin ) {
      return;
    }
    document.getElementById(loginToggle).classList.remove('active');
    document.getElementById(loginToggle + "Body").style.display = "none";
    document.getElementById(loginToggle + "Footer").style.display = "none";
    loginToggle = target.id
    document.getElementById(loginToggle).classList.add('active');
    document.getElementById(loginToggle + "Body").style.display = "block";
    document.getElementById(loginToggle + "Footer").style.display = "block";
  }

  // make the switcher buttons more responsive
  function HighlightLoginModal(targetID, turnOn) {
    // can't do anything while we're processing
    if( processingLogin ) {
      return;
    }
    if( targetID != loginToggle ) {
      if( turnOn ) {
        document.getElementById(loginToggle).classList.remove('active');
      } else {
        document.getElementById(loginToggle).classList.add('active');
      }
    }
  }

  // process an attempted login
  function SubmitLogIn() {
    // can't do anything while we're processing
    if( processingLogin ) {
      return;
    }

    // we need to give this a few frames to load before we test for error messages
    $('#loginFrame').load( function() { setTimeout( function() { 
      var frame = document.getElementById("loginFrame");
      frame.onload = null;

      var messages = frame.contentDocument.getElementById("loginFlashMessages");
      // success, reload this page
      if( messages == null || messages.children.length == 0 ) {
        location.reload(true);
      // failure, find the error message and display it in the modal
      } else {
        processingLogin = false;
        document.getElementById(loginToggle + "Footer").style.display = "block";
        document.getElementById("loadingFooter").style.display = "none";
        document.getElementById("loginFlashMessages").innerHTML = messages.innerHTML;
      }
    }, 100); } );

    // make sure they've given us all the relevant info
    var barcode = document.getElementById("login_username");
    var pword = document.getElementById("login_password");
    if( barcode.value == "" || barcode.value == "Enter your Barcode" ) {
      document.getElementById("login_usernameError").style.display = "block";
      document.getElementById("login_usernameError").innerHTML = "Please enter your barcode above.";
      if( "classList" in barcode ) {
        barcode.classList.add("textBoxError");
      } else {
        barcode.className += " textBoxError";
      }
      barcode.nextElementSibling.style.display = "block";
    } else if( pword.value == "" || pword.value == "Enter your PIN" ) {
      document.getElementById("login_passwordError").style.display = "block";
      document.getElementById("login_passwordError").innerHTML = "Please enter your PIN above.";
      if( "classList" in pword ) {
        pword.classList.add("textBoxError");
      } else {
        pword.className += " textBoxError";
      }
      pword.nextElementSibling.style.display = "block";
    } else {
      processingLogin = true;
      document.getElementById(loginToggle + "Footer").style.display = "none";
      document.getElementById("loadingFooter").style.display = "block";
      document.getElementById("loginForm").submit();
    }
  }

  // clean out the error problems
  function ClearFormError(element) {
    if( "classList" in element ) {
      element.classList.remove("textBoxError");
    } else {
      element.className = element.className.replace("textBoxError", "");
    }
    document.getElementById(element.id + "Error").style.display = "none";
    element.nextElementSibling.style.display = "none";
  }

  // submit the login on enter press
  $("#loginForm input").keypress(function(event) {
    if (event.which == 13) {
      event.preventDefault();
      SubmitLogIn();
    }
  });
</script>
