<?
  // Set page title.
  $this->headTitle($this->translate('Changes to Library Catalog'));
?>
<div class="EIN-col-m-12">
  <div class="privacyTitle">
    <?=$this->translate('Changes to Library Catalog')?>
  </div>
  <div class="privacyText">
    <br><div class="privacyHeader">June 13, 2017</div><br>
    <ul>
      <li>The new mobile-friendly design of the catalog has launched! Check it out and provide us with <a href="https://www.surveymonkey.com/r/5SLSW8Y" target="_blank">any feedback you may have</a>. 
          We hope you like it!</li>
    </ul>
  </div><br>
</div>