<?
  // Set page title.
  $this->headTitle($this->translate('Changes to Library Catalog'));
?>
<div class="EIN-col-m-12">
  <div class="privacyTitle">
    <?=$this->translate('Changes to Library Catalog')?>
  </div>

  <div class="privacyText">
    <br><div class="privacyHeader">June 26, 2017</div><br>
    <div>
      Thank you for your survey feedback!   Your input has been invaluable and we are working to make changes.   Below are updates about some of the changes.  <a href="https://www.surveymonkey.com/r/5SLSW8Y" target="_blank">Please let us know what you think.</a>
    </div><br>
    <div>
      <p class="privacyHeader">The updated Library Catalog is frequently very slow.</p>
      <p>There have been multiple issues with slowness in the Library Catalog particularly this past weekend.  We apologize for this and are working very hard to address these problems.   Much of this has been caused by some underlying technology issues with another system that the Library Catalog must use to provide you with information about your library account.  We made some changes today (June 27th) to improve performance, and will continue to investigate additional options.  Thank you for your patience! </p>
    </div><br>
    <div>
      <p class="privacyHeader">My library card number and PIN are no longer remembered on my device!</p>
      <p>We take the privacy of your library information very seriously. The new system remembers your library card number and PIN on a device used outside the library. You must log into the new system at least once for the system to remember your credentials. If you click the Log Out button (from the Account menu), your credentials are forgotten and you will need to re-enter them the  next time.</p>
      <p>It has always been the case that your library card number and PIN are never remembered when accessing the catalog from any device inside the library.  These are “public” workstations accessible by any library user. </p>
    </div><br>
    <div>
      <p class="privacyHeader">I don’t see all my checked out items or holds (requests)!</p>
      <p>There was a problem for people who had more than 50 items checked out or more than 50 holds.  You were not able to view all of your checked out items or holds on the respective pages. This has been fixed and all items are now displaying.</p>
    </div><br>
    <div>
      <p class="privacyHeader">What happened to the Fiction/Nonfiction search filter? </p>
      <p>Back by popular demand! The Fiction/Nonfiction facet has been re-enabled.</p>
    </div><br>
    <div>
      <p class="privacyHeader">The Hold I just placed isn’t appearing in My Account!</p>
      <p>It can take a few minutes for a hold request to propagate through the system.  This is another aspect of the overall slowness that you may have seen.</p>
      <p>We have also added a button to the Holds page to <span class="bold">Refresh</span> your list of holds.</p>
    </div><br>
    <div>
      <p class="privacyHeader">Are “Holds” the same as “Requests”?</p>
      <p>Yes.</p>
    </div><br>
    <div>
      <p class="privacyHeader">I got a strange error message that I didn’t understand while renewing items or placing holds.</p>
      <p>This is another symptom of the overall reported system slowness.  In most cases your action was successful, but this was not clear due to the error.  Some changes have been made to improve the overall system performance and provide better error messages when necessary.</p>
    </div><br>
  </div><br>
  <div class="privacyText">
    <br><div class="privacyHeader">June 13, 2017</div><br>
    <div>The new mobile-friendly design of the catalog has launched! Check it out and provide us with <a href="https://www.surveymonkey.com/r/5SLSW8Y" target="_blank">any feedback you may have</a>.
          We hope you like it!  </div>
  </div><br>
</div>
