<?
  // Set page title.
  $this->headTitle($this->translate('Changes to Library Catalog'));
?>
<div class="EIN-col-m-12">
  <div class="privacyTitle">
    <?=$this->translate('Changes to Library Catalog')?>
  </div>
    <div>
      Thank you for your survey feedback!   Your input has been invaluable and we are working to make improvements.   Below are updates about some of the changes.  <a href="https://www.surveymonkey.com/r/5SLSW8Y" target="_blank">Please let us know what you think.</a>
   </div><br>
   <div class="privacyText">
     <br><div class="privacyHeader">August 4, 2017</div><br>
     <div>
       <p class="privacyHeader">I need to know if an item is available at the libraries I typically use.</p>
       <div>
         <p>Based on your feedback, we've made a few changes to simplify locating available items:</p>
         <ul>
           <li>Enhanced availability tags:<br>
           Availability tags now indicate whether a title has available copies and where they are located.  When logged in to your library account, “Available at your preferred libraries” indicates that there is an available item at your preferred, alternate, or home library (the library that serves the home address in your patron record).  When searching from inside the library, “It’s here!” indicates that there is an available item at your current location and “Available at other Libraries” means that there is an available copy at another library.</li>
           <li>Location filter:<br>
           If you are logged in to your library account, your preferred libraries will appear at the top of the list.  When filtering by location from inside the library, the library you are currently visiting appears at the top of the list of libraries.</li>
           <li>Availability details:<br>
           If you are logged in to your library account, items at your preferred libraries will appear at the top of the list.  When viewing Availability Details on the item detail page from inside the library, items at the library you are currently visiting appear at the top of the list.</li>
         </ul>
       </div>
     </div><br>
     <div>
       <p class="privacyHeader">My library card number and PIN are still not remembered on my device!</p>
       <p>As <a href="#credentials">mentioned previously</a>, your login information is remembered on your device after the first time you log in and it is erased upon logging out.  We have received a few reports that this feature is still not working for some people.  In other cases where multiple people access different library accounts on the same device this is problematic because only one person’s login information can be saved at any given time.  Thank you for your feedback and please be aware that we are working on a solution to improve this process for all Library Catalog users.</p>
     </div><br>
     <div>
       <p class="privacyHeader">Why am I prompted to Register when I already have a library card?</p>
       <p>Many people reported confusion related to the "Register" button that appeared when prompted to log in to your accounts. The login prompt has been updated to clarify the login process for those who already have a library card.</p>
     </div><br>
     <div>
       <p class="privacyHeader">I see an error message when trying to request multiple items in my Book Cart.</p>
       <p>When attempting to place holds on multiple items in your Book Cart or one of your lists, they all failed and an error message was displayed.  This issue has been fixed.  </p>
     </div><br>
   </div>
    <div class="privacyText">
    <br><div class="privacyHeader">July 26, 2017</div><br>
    <div>
	 <p class="privacyHeader">When placing a hold, my library is not listed as a pickup location.</p>
	 <p>This affected people without any Preferred Libraries selected in their Library Catalog profile.  A fix has been implemented and now your home library appears in the list, even if you have not chosen any Preferred Libraries.</p>
	 <p class="privacyHeader">A blank page displays when I log in to my Account.</p>
	 <p>Some library customers experienced this when logging in to their accounts directly from their library's website. Changes were made to ensure that you are routed to the correct page upon logging in.</p>
    </div>
	  </div><br>
  <div class="privacyText">
    <br><div class="privacyHeader">June 26, 2017</div><br>
    <div>
      <p class="privacyHeader">The updated Library Catalog is frequently very slow.</p>
      <p>There were multiple issues with slowness in the Library Catalog particularly the weekend of June 24th.  We apologize for this and are working very hard to address these problems.   Much of this has been caused by some underlying technology issues with another system that the Library Catalog must use to provide you with information about your library account.  We made some changes today (June 26th) to improve performance, and will continue to investigate additional options.  Thank you for your patience! </p>
    </div><br>
    <div>
      <p id="credentials" class="privacyHeader">My library card number and PIN are no longer remembered on my device!</p>
      <p>We take the privacy of your library information very seriously. The new system remembers your library card number and PIN on a device used outside the library. You must log into the new system at least once for the system to remember your credentials. If you click the Log Out button (from the Account menu), your credentials are forgotten and you will need to re-enter them the  next time.</p>
      <p>It has always been the case that your library card number and PIN are never remembered when accessing the catalog from any device inside the library.  These are “public” workstations accessible by any library user. </p>
    </div><br>
    <div>
      <p class="privacyHeader">I don’t see all my checked out items or holds (requests)!</p>
      <p>There was a problem for people who had more than 50 items checked out or more than 50 holds.  You were not able to view all of your checked out items or holds on the respective pages. This has been fixed and all items are now displaying.</p>
    </div><br>
    <div>
      <p class="privacyHeader">What happened to the Fiction/Nonfiction search filter? </p>
      <p>Back by popular demand! The Fiction/Nonfiction facet has been re-enabled.</p>
    </div><br>
    <div>
      <p class="privacyHeader">The Hold I just placed isn’t appearing in My Account!</p>
      <p>It can take a few minutes for a hold request to propagate through the system.  This is another aspect of the overall slowness that you may have seen.</p>
      <p>We have also added a button to the Holds page to <span class="bold">Refresh</span> your list of holds.</p>
    </div><br>
    <div>
      <p class="privacyHeader">Are “Holds” the same as “Requests”?</p>
      <p>Yes.</p>
    </div><br>
    <div>
      <p class="privacyHeader">I got a strange error message that I didn’t understand while renewing items or placing holds.</p>
      <p>This is another symptom of the overall reported system slowness.  In most cases your action was successful, but this was not clear due to the error.  Some changes have been made to improve the overall system performance and provide better error messages when necessary.</p>
    </div><br>
  </div><br>
  <div class="privacyText">
    <br><div class="privacyHeader">June 13, 2017</div><br>
    <div>The new mobile-friendly design of the catalog has launched! Check it out and provide us with <a href="https://www.surveymonkey.com/r/5SLSW8Y" target="_blank">any feedback you may have</a>.
          We hope you like it!  </div>
  </div><br>
</div>
