<hr/>
<div class="row footer">
  <table class="footer">
    <tr><td>&nbsp;</td></tr>
    <tr><td>
      <a href="http://radworkshere.org" target="_blank"><div class="RADLogo"></div></a>
<!-- Button to link people to form for submitting problems -->
      <a href="https://docs.google.com/forms/d/e/1FAIpQLScaTA97sfg-d1in_3UuOLGX4JqgNBWaqRCh-ViXDmuzSXFwCQ/viewform" target="_blank"><div class="feedbackButton gap">Feedback or problem?<br>Report it here!</div></a>
<!-- -->
      <a href="http://www.einetwork.net" target="_blank"><div class="EINLogo gap"></div></a>
    </td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>
      Library Catalog is a service of eiNetwork, a collaboration of the <a href="http://www.aclalibraries.org" target="_blank">Allegheny County Library Association</a> and <a href="http://www.carnegielibrary.org" target="_blank">Carnegie Library of Pittsburgh</a>.
    </td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>
      <a href="#" target="_blank" onclick="Lightbox.get('MyResearch','comingsoon'); return false;" style="display:none">Locations</a>
      <a href="#" target="_blank" onclick="Lightbox.get('Help','Home'); return false;"><!-- class="gap"-->Help</a>
      <a href="http://www.einetwork.net/ils/requests/acquire_web_ngc.php" target="_blank" class="gap">Suggest a Purchase</a>
    </td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>&copy;eiNetwork</td></tr>
    <tr><td>&nbsp;</td></tr>
  </div>
</div>
