<?
  $account = $this->auth()->getManager();
  if( $user = $account->isLoggedIn() ) {
    $displayName = $user->firstname . " " . $user->lastname;
    $displayName = ucwords( strtolower( $displayName ) );
  }
?>
<div class="navbar-header row">
  <div class="EIN-col-m-12">
    <div style="float:left;margin-right:20px">
      <a href="<?=$this->url('home')?>"><button class="btn-noBorderAlternate">Library Catalog</button></a>
    </div>
    <div class="floatR">
      <div class="dropdown EIN-hide">
        <button type="button" class="dropdown-toggle btn-noBorderAlternate" data-toggle="dropdown" href="#navDropdown">
          <span class="sr-only">Toggle navigation</span>
          <i class="fa fa-bars"></i>
        </button>
      </div>
      <button class="EIN-hide-m EIN-hide-t btn-noBorderAlternate"><span class="headerLink">Help</span></button>
      <button class="EIN-hide-m EIN-hide-t btn-noBorderAlternate"><span class="headerLink">Locations</span></button>
<? if ($user): ?>
      <button class="EIN-hide-m EIN-hide-t btn-noBorderAlternate" data-toggle="dropdown" data-target="#navDropdown"><span class="headerLink">Account<i class="fa fa-caret-down" style="margin-left:4px;margin-bottom:5px"></i></span></button>
<? else: ?>
      <button class="EIN-hide-m EIN-hide-t btn-noBorderAlternate" onClick="Lightbox.get('MyResearch', 'Login')"><span class="headerLink">Log In or Register</span></button>
<? endif; ?>
    </div>
<? if ($this->layout()->searchbox !== false): ?>
    <span class="expand"><div class="EIN-hide-m EIN-col-t-12" style="border-left:1px solid #949494;border-right:1px solid #949494;padding-right:2px">
      <?=$this->layout()->searchbox ?>
    </div></span>
<? endif; ?>
  </div>
  <div class="EIN-hide-m EIN-col-t-12 EIN-col-12" style="border-top:1px solid #949494"></div>
  <div class="EIN-col-m-12">
    <hr class="EIN-hide-t EIN-hide">
    <div class="EIN-col-m-12 dropdown" id="navDropdown">
      <ul role="navigation" class="dropdown-menu whiteDropdown<?= ($user ? "" : " EIN-hide")?>">
<? if( $user): ?>
  <? $listCount = 0; $bookCartCount = 0; ?>
  <? foreach( $user->getLists() as $list ): ?>
    <? if( $list->isBookCart() ): ?>
      <? $bookCartCount = $list->count(); ?>
    <? else: ?>
      <? $listCount++; ?>
    <? endif; ?>
  <? endforeach; ?>
        <li class="loggedInName"><?= $displayName ?></li>
        <li><button class="btn-dropdown btn-whiteDropdown">Message Center<span class="badge">2</span></button></li>
        <li><a href="<?=$this->url('myresearch-mylist')?>"><button class="btn-dropdown btn-whiteDropdown">Lists<? if($listCount>0): ?><span class="badge"><?=$listCount?></span><? endif; ?></button></a></li>
        <li><a href="<?=$this->url('myresearch-bookcart')?>"><button class="btn-dropdown btn-whiteDropdown">Book Cart<? if($bookCartCount>0): ?><span class="badge"><?=$bookCartCount?></span><? endif; ?></button></a></li>
        <li><a href="<?=$this->url('myresearch-holds')?>"><button class="btn-dropdown btn-whiteDropdown">Holds</button></a></li>
        <li><a href="<?=$this->url('myresearch-checkedout')?>"><button class="btn-dropdown btn-whiteDropdown">Checked Out</button></a></li>
        <li><button class="btn-dropdown btn-whiteDropdown">Saved Searches</button></li>
        <li><button class="btn-dropdown btn-whiteDropdown">Reading History</button></li>
        <li><a href="<?=$this->url('myresearch-profile')?>"><button class="btn-dropdown btn-whiteDropdown">Profile</button></a></li>
        <hr class="stretchHR">
        <li><button class="btn-dropdown btn-whiteDropdown EIN-hide">Help</button></li>
        <li><button class="btn-dropdown btn-whiteDropdown EIN-hide">Locations</button></li>
        <li><a href="<?=$this->url('myresearch-logout')?>"><button class="btn-dropdown btn-whiteDropdown"><i class="fa fa-sign-out"></i>Log Out</button></a></li>
<? else: ?>
        <li><button class="btn-dropdown btn-whiteDropdown">Help</button></li>
        <li><button class="btn-dropdown btn-whiteDropdown">Locations</button></li>
        <li><button class="btn-dropdown btn-whiteDropdown" onClick="Lightbox.get('MyResearch', 'Login')">Log In or Register</button></li>
<? endif; ?>
      </ul>
    </div>
    <div class="EIN-col-m-12 dropdown" id="searchBoxDropdown">
      <ul role="navigation" class="dropdown-menu standardDropdown searchDropdown">
        <li><button class="btn-dropdown btn-standardDropdown">Saved Searches</button></li>
        <li><button class="btn-dropdown btn-standardDropdown">Advanced Search</button></li>
      </ul>
    </div>
  </div>
  <div class="EIN-col-m-12 EIN-hide-t EIN-hide">
<? if ($this->layout()->searchbox !== false): ?>
    <?=$this->layout()->searchbox ?>
    <hr>
<? endif; ?>
  </div>
  <div class="EIN-col-m-12" style="height:10px"></div>
</div>
