<div class="EIN-col-m-12" style="height:20px"></div>
<div class="EIN-col-m-12">
  <? if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
    <fieldset class="EIN-col-m-12">
      <label class="EIN-col-m-12 advSearchGroupTitle center"><?=$this->transEsc('Limit To')?></label>
      <? if (!empty($this->checkboxFacets)): ?>
        <?=$this->render('search/advanced/checkbox-filters.phtml')?>
      <? endif; ?>
      <div class="EIN-col-m-12">
        <? foreach ($this->facetList as $field => $list): ?>
          <table style="width:100%"><tr>
            <td class="EIN-hide-m EIN-col-t-2">&nbsp;</td>
            <td class="EIN-col-m-12 EIN-col-t-8">
              <div class="panel panel-advSearchAccordion">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <a data-toggle="collapse" class="facetAccordionTitle collapsed" href="#facet<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>">
                      <i class="fa fa-check greenCheck" style="float:none;display:none"></i>
                      <?=$this->transEsc($list['label'])?>
                      <i class="fa fa-caret-down"></i>
                      <i class1="fa fa-caret-up"></i>
                    </a>
                  </h4>
                </div>
                <div id="facet<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" class="facetAccordionContent panel-collapse collapse">
                  <div class="panel-body">
                    <ul class="facetAccordionList">
                      <? if( $field != "format" ): ?>
                        <?
                          // Sort the current facet list alphabetically; we'll use this data
                          // along with the foreach below to display facet options in the
                          // correct order.
                          $sorted = array();
                          foreach ($list['list'] as $i => $value) {
                            if (!empty($value['displayText'])) {
                              $sorted[$i] = $value['displayText'];
                            }
                          }
                          natcasesort($sorted);
                        ?>
                        <? foreach ($sorted as $i => $display): ?>
                          <? $value = $list['list'][$i]; ?>
                          <li value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>">
                            <i class="fa fa-check-square facetToggleOff" onClick="ToggleFacet($(this).next());ToggleFacet($(this));CleanChecks();"></i>
                            <i class="fa fa-square-o facetToggleOn" onClick="ToggleFacet($(this).prev());ToggleFacet($(this));CleanChecks();"></i>
                            <?=$this->escapeHtml($display)?>
                          </li>
                        <? endforeach; ?>
                      <? else: ?>
                        <? $inputVals = $list['list']; ?>
                        <? $outputVals = []; ?>
                        <? foreach($this->formatCategories->types as $category): ?>
                          <? $formatTypes = explode(",", $category); ?>
                          <? $categoryName = array_splice($formatTypes, 0, 1)[0]; ?>
                          <? $outputVals[$categoryName] = ["someApplied" => false, "allApplied" => true, "children" => []]; ?>
                          <? foreach( $formatTypes as $needleFormat): ?>
                            <? foreach( $inputVals as $index => $haystackFormat): ?>
                              <? if( $needleFormat == $haystackFormat["value"] ): ?>
                                <? $outputVals[$categoryName]["children"][] = array_splice($inputVals, $index, 1)[0]; ?>
                                <? $outputVals[$categoryName]["someApplied"] |= $haystackFormat["isApplied"]; ?>
                                <? $outputVals[$categoryName]["allApplied"] &= $haystackFormat["isApplied"]; ?>
                              <? endif; ?>
                            <? endforeach; ?>
                          <? endforeach; ?>
                        <? endforeach; ?>
                        <? $bookTypes = ["Print Book", "eBook", "Audio Book"]; $showBooks = false; foreach($bookTypes as $type): $showBooks |= (count($outputVals[$type]["children"]) > 0); endforeach; ?>
                        <? if( $showBooks ): ?>
                          <li class="facetOffset0">
                            <i class="fa fa-check-square facetToggleOff categoryCheck" onClick="ToggleCategory($(this));CleanChecks();"></i>
                            <i class="fa fa-minus-square-o facetToggleOff categoryCheck" onClick="ToggleCategory($(this));CleanChecks();"></i>
                            <i class="fa fa-square-o facetToggleOn categoryCheck" onClick="ToggleCategory($(this));CleanChecks();"></i>
                            <?=$this->escapeHtml("Books")?>
                          </li>
                        <? endif; ?>
                        <? foreach( $outputVals as $type => $thisArray ): ?>
                          <? if( count($thisArray["children"]) > 0 ): ?>
                            <li class="facetOffset<?=(in_array($type, $bookTypes) ? "1" : "0")?>">
                              <i class="fa fa-check-square facetToggleOff categoryCheck" onClick="ToggleCategory($(this));CleanChecks();"></i>
                              <i class="fa fa-minus-square-o facetToggleOff categoryCheck" onClick="ToggleCategory($(this));CleanChecks();"></i>
                              <i class="fa fa-square-o facetToggleOn categoryCheck" onClick="ToggleCategory($(this));CleanChecks();"></i>
                              <?=$this->escapeHtml($type)?>
                            </li>
                            <? foreach( $thisArray["children"] as $thisFacet ): ?>
                              <li class="facetOffset<?=(in_array($type, $bookTypes) ? "2" : "1")?>" value="<?=$this->escapeHtmlAttr(($thisFacet['operator'] == 'OR' ? '~' : '') . $field . ':"' . $thisFacet['value'] . '"')?>">
                                <i class="fa fa-check-square facetToggleOff" onClick="ToggleFacet($(this).next());ToggleFacet($(this));CleanChecks();"></i>
                                <i class="fa fa-square-o facetToggleOn" onClick="ToggleFacet($(this).prev());ToggleFacet($(this));CleanChecks();"></i>
                                <?=$this->escapeHtml($thisFacet['displayText'])?>
                              </li>
                            <? endforeach; ?>
                          <? endif; ?>
                        <? endforeach; ?>
                        <? if( count($inputVals) > 0 ): ?>
                          <li class="facetOffset0">
                            <i class="fa fa-check-square facetToggleOff categoryCheck" onClick="ToggleCategory($(this));CleanChecks(false);"></i>
                            <i class="fa fa-minus-square-o facetToggleOff categoryCheck" onClick="ToggleCategory($(this));CleanChecks(false);"></i>
                            <i class="fa fa-square-o facetToggleOn categoryCheck" onClick="ToggleCategory($(this));CleanChecks(false);"></i>
                            <?=$this->escapeHtml("Other")?>
                          </li>
                          <? usort($inputVals, function ($format1,$format2) { return strcmp($format1["displayText"], $format2["displayText"]); }); ?>
                          <? foreach( $inputVals as $thisFacet ): ?>
                            <li class="facetOffset1" value="<?=$this->escapeHtmlAttr(($thisFacet['operator'] == 'OR' ? '~' : '') . $field . ':"' . $thisFacet['value'] . '"')?>">
                              <i class="fa fa-check-square facetToggleOff" onClick="ToggleFacet($(this).next());ToggleFacet($(this));CleanChecks();"></i>
                              <i class="fa fa-square-o facetToggleOn" onClick="ToggleFacet($(this).prev());ToggleFacet($(this));CleanChecks();"></i>
                              <?=$this->escapeHtml($thisFacet['displayText'])?>
                            </li>
                          <? endforeach; ?>
                        <? endif; ?>
                      <? endif; ?>
                    </ul>
                  </div>
                </div>
                <select class="form-control" id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10" style="display:none">
                  <? foreach ($list['list'] as $item): ?>
                    <option value="<?=$this->escapeHtmlAttr(($item['operator'] == 'OR' ? '~' : '') . $field . ':"' . $item['value'] . '"')?>"<?=(isset($item['selected']) && $item['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($item['displayText'])?></option>
                  <? endforeach; ?>
                </select>
              </div>
            </td>
            <td class="EIN-hide-m EIN-col-t-2">&nbsp;</td>
          </tr></table>
        <? endforeach; ?>
      </div>
    </fieldset>
  <? endif; ?>
  <div class="EIN-col-m-12">
    <? if (isset($this->illustratedLimit)): ?>
      <fieldset class="EIN-col-m-12">
          <table style="width:100%"><tr>
            <td class="EIN-hide-m EIN-col-t-2">&nbsp;</td>
            <td class="EIN-col-m-12 EIN-col-t-8">
            <div class="panel panel-advSearchAccordion">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" class="facetAccordionTitle collapsed" href="#facetIllustrated">
                    <i class="fa fa-check greenCheck" style="float:none;display:none"></i>
                    <?=$this->transEsc("Illustrated")?>
                    <i class="fa fa-caret-down"></i>
                    <i class="fa fa-caret-up"></i>
                  </a>
                </h4>
              </div>
              <div id="facetIllustrated" class="facetAccordionContent panel-collapse collapse">
                <div class="panel-body">
                  <ul class="facetAccordionList">
                    <? foreach ($this->illustratedLimit as $current): ?>
                      <li value="<?=$this->escapeHtmlAttr($current['value'])?>">
                        <i class="fa fa-check-circle facetToggle<?=($current['selected']?"On":"Off") . (($current['value']==-1)?"":" showCheck")?>" onClick="ChangeRadio($(this));CleanChecks();"></i>
                        <i class="fa fa-circle-o facetToggle<?=$current['selected']?"Off":"On"?>" onClick="ChangeRadio($(this));CleanChecks();"></i>
                        <?=$this->transEsc($current['text'])?>
                        <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?> style="display:none"/>
                      </li>
                    <? endforeach; ?>
                  </ul>
                </div>
              </div>
            </div>
          </td>
          <td class="EIN-hide-m EIN-col-t-2 EIN-col-2">&nbsp;</td>
        </tr></table>
      </fieldset>
    <? endif; ?>
    <div class="EIN-col-m-12" style="height:10px"></div>
    <?=$this->render('search/advanced/limit.phtml')?>
    <?=$this->render('search/advanced/ranges.phtml')?>
  </div>
</div>
<script type="text/javascript">
  function ChangeRadio(item) {
    $(item).parents('.panel').find('.fa-check-circle').removeClass('facetToggleOn').addClass('facetToggleOff');
    $(item).parents('.panel').find('.fa-circle-o').removeClass('facetToggleOff').addClass('facetToggleOn');
    $(item).parents('li').find('.fa-check-circle').removeClass('facetToggleOff').addClass('facetToggleOn');
    $(item).parents('li').find('.fa-circle-o').removeClass('facetToggleOn').addClass('facetToggleOff');
    $(item).parents('.panel').find('input[value="' + $(item).parent().attr('value').replace(/\"/g, "\\\"")+ '"]').prop('checked', true);
  }

  function ToggleFacet(item) {
    if(item.hasClass('facetToggleOn')) {
      item.removeClass('facetToggleOn');
      item.addClass('facetToggleOff');
      $(item).parents('.panel').find('option[value="' + $(item).parent().attr('value').replace(/\"/g, "\\\"")+ '"]').prop('selected', item.hasClass('fa-square-o'));
    } else {
      item.removeClass('facetToggleOff');
      item.addClass('facetToggleOn');
    }
  }

  function ToggleCategory(item) {
    // flip all of the descendents to off if the clicked category is on, otherwise flip them all to on
    var p = $(item).parent().get()[0];
    var stopSign = "." + p.className + ((p.className == "facetOffset1") ? ",.facetOffset0" : "");
    var targetClass = item.hasClass("fa-check-square") ? "fa-square-o" : "fa-check-square";
    $(p).nextUntil(stopSign).children('.' + targetClass).removeClass('facetToggleOff').addClass('facetToggleOn');
    $(p).nextUntil(stopSign).children('.fa').not('.' + targetClass).removeClass('facetToggleOn').addClass('facetToggleOff');
    $(p).nextUntil(stopSign).children('.fa.facetToggleOn').not('.categoryCheck').each( function() {
      $(this).parents('.panel').find('option[value="' + $(this).parent().attr('value').replace(/\"/g, "\\\"")+ '"]').prop('selected', !($(this).hasClass('fa-square-o')));
    } );
  }

  function CleanChecks() {
    // fix all of the category states in the format section
    $.each($('#facetformat').find('.facetOffset1'), function(index, item) {
      // ignore the ones that aren't categories
      if( $(item).children('i.categoryCheck').length > 0 ) {
        $(item).children('.fa').removeClass('facetToggleOn');
        $(item).children('.fa').addClass('facetToggleOff');
        if( $(item).nextUntil('.facetOffset1,.facetOffset0').length == $(item).nextUntil('.facetOffset1,.facetOffset0').find('.fa-check-square.facetToggleOn').length ) {
          $(item).children('.fa-check-square').removeClass('facetToggleOff');
          $(item).children('.fa-check-square').addClass('facetToggleOn');
        } else if( $(item).nextUntil('.facetOffset1,.facetOffset0').find('.fa-check-square.facetToggleOn').length > 0 ) {
          $(item).children('.fa-minus-square-o').removeClass('facetToggleOff');
          $(item).children('.fa-minus-square-o').addClass('facetToggleOn');
        } else {
          $(item).children('.fa-square-o').removeClass('facetToggleOff');
          $(item).children('.fa-square-o').addClass('facetToggleOn');
        }
      }
    } );
    $.each($('#facetformat').find('.facetOffset0'), function(index, item) {
      $(item).children('.fa').removeClass('facetToggleOn');
      $(item).children('.fa').addClass('facetToggleOff');
      if( $(item).nextUntil('.facetOffset0').length == $(item).nextUntil('.facetOffset0').find('.fa-check-square.facetToggleOn').length ) {
        $(item).children('.fa-check-square').removeClass('facetToggleOff');
        $(item).children('.fa-check-square').addClass('facetToggleOn');
      } else if( $(item).nextUntil('.facetOffset0').find('.fa-check-square.facetToggleOn').length > 0 ) {
        $(item).children('.fa-minus-square-o').removeClass('facetToggleOff');
        $(item).children('.fa-minus-square-o').addClass('facetToggleOn');
      } else {
        $(item).children('.fa-square-o').removeClass('facetToggleOff');
        $(item).children('.fa-square-o').addClass('facetToggleOn');
      }
    } );
    // turn on all of the needed checkmarks
    $.each($('.panel-advSearchAccordion'), function(index, item) {
      if( $(item).find('.facetToggleOn.fa-check-square,.facetToggleOn.fa-check-circle.showCheck').length > 0 ) {
        $(item).find('.greenCheck').css('display', 'inline-block');
      } else {
        $(item).find('.greenCheck').css('display', 'none');
      }
    } );
  }
</script>