<input class="checkbox-select-item" type="checkbox" name="ids[]" value="<?=$this->escapeHtmlAttr($this->id) ?>" onchange="ToggleRecordCheck(this)"/>
<input type="hidden" name="idsAll[]" value="<?=$this->escapeHtmlAttr($this->id) ?>"/>
<script type="text/javascript">
  function ToggleRecordCheck(target) {
    var parentForm = $(target).parents('.ajaxItem').siblings('form');
    parentForm.find('.checkbox-select-item[value=\'' + $(target).attr('value') + '\']').prop('checked',target.checked);
    parentForm.find('.checkbox-select-all').prop('checked', true);
    parentForm.find('.checkbox-select-item').each( function() {
      parentForm.find('.checkbox-select-all').prop('checked', parentForm.find('.checkbox-select-all').prop('checked') && this.checked);
    } );
    ScanBulkButton(parentForm);
  }
</script>
