<h2><?=$this->transEsc(($this->changePickup?"Change ":"")."Pickup Location")?></h2>
<div class="hold-form">
  <table class="pickupLocationTable">
    <tr><td colspan="2" class="modalSubheading center">Preferred</td></tr>
    <? $showPreferredLibrary = isset($this->preferredLibrary); ?>
    <? $showAlternateLibrary = isset($this->alternateLibrary) && (!isset($this->preferredLibrary) || ($this->alternateLibrary != $this->preferredLibrary)); ?>
    <? $showHomeLibrary = isset($this->homeLibrary) && (!isset($this->preferredLibrary) || ($this->homeLibrary != $this->preferredLibrary)) && (!isset($this->alternateLibrary ) || ($this->homeLibrary != $this->alternateLibrary)); ?>
    <? $selectedID = $showPreferredLibrary ? $this->preferredLibrary : ($showAlternateLibrary ? $this->alternateLibrary : ($showHomeLibrary ? $this->homeLibrary : "")) ?>
    <? foreach ($this->pickup as $lib): ?>
      <? if($showPreferredLibrary && $this->preferredLibrary == $lib['locationID'] ): ?>
        <tr>
          <td><i class="fa fa-check bigGreenCheck" name="check-<?=$this->escapeHtmlAttr($lib['locationID']).(($lib['locationID'] == $selectedID)?"":"\" style=\"color:#fff")?>"></i></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocationPreferred" onclick="return SelectPickupLocation('<?=$this->escapeHtmlAttr($lib['locationID'])?>');"><?=$this->escapeHtml($lib['locationDisplay'])?></button></td>
        </tr>
        <? break; ?>
      <? endif; ?>
    <? endforeach; ?>
    <? foreach ($this->pickup as $lib): ?>
      <? if($showAlternateLibrary && $this->alternateLibrary == $lib['locationID'] ): ?>
        <tr>
          <td><i class="fa fa-check bigGreenCheck" name="check-<?=$this->escapeHtmlAttr($lib['locationID']).(($lib['locationID'] == $selectedID)?"":"\" style=\"color:#fff")?>" style="color:#fff"></i></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocationPreferred" onclick="return SelectPickupLocation('<?=$this->escapeHtmlAttr($lib['locationID'])?>');"><?=$this->escapeHtml($lib['locationDisplay'])?></button></td>
        </tr>
        <? break; ?>
      <? endif; ?>
    <? endforeach; ?>
    <? foreach ($this->pickup as $lib): ?>
      <? if($showHomeLibrary && $this->homeLibrary == $lib['locationID'] ): ?>
        <tr>
          <td><i class="fa fa-check bigGreenCheck" name="check-<?=$this->escapeHtmlAttr($lib['locationID']).(($lib['locationID'] == $selectedID)?"":"\" style=\"color:#fff")?>" style="color:#fff"></i></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocationPreferred" onclick="return SelectPickupLocation('<?=$this->escapeHtmlAttr($lib['locationID'])?>');"><?=$this->escapeHtml($lib['locationDisplay'])?> (Home)</button></td>
        </tr>
        <? break; ?>
      <? endif; ?>
    <? endforeach; ?>
    <tr><td colspan="2"><div class="modal-break"></div></td></tr>
    <tr><td colspan="2" class="modalSubheading center">Others</td></tr>
    <? foreach ($this->pickup as $lib): ?>
      <? if((!isset($this->preferredLibrary) || ($this->preferredLibrary != $lib['locationID'])) && 
            (!isset($this->alternateLibrary) || ($this->alternateLibrary != $lib['locationID'])) && 
            (!isset($this->homeLibrary)      || ($this->homeLibrary != $lib['locationID']))): ?>
        <tr>
          <td><i class="fa fa-check bigGreenCheck" name="check-<?=$this->escapeHtmlAttr($lib['locationID']).(($lib['locationID'] == $selectedID)?"":"\" style=\"color:#fff")?>" style="color:#fff"></i></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocation" onclick="return SelectPickupLocation('<?=$this->escapeHtmlAttr($lib['locationID'])?>');"><?=$this->escapeHtml($lib['locationDisplay'])?></button></td>
        </tr>
      <? endif; ?>
    <? endforeach; ?>
  </table>
</div>
<div class="modal-footer">
  <div id="holdFooter">
    <form action="" class="form-horizontal" method="post" name="placeHold" target="loginFrame">
      <input type="hidden" name="gatheredDetails[comment]" value="" />
      <input type="hidden" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>"/>
      <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$selectedID?>">
      <input type="hidden" name="placeHold" value="1">
      <? if( $this->changePickup ): ?>
        <input type="hidden" name="changePickup" value="true">
        <input type="hidden" name="referrer" value="<?=$this->referrer?>">
        <? foreach( $this->ids as $id ): ?>
          <input type="hidden" name="updateIDs[]" value="<?=$id?>">
        <? endforeach; ?>
      <? endif; ?>
      <button class="btn-default btn-wide"<?=(isset($this->preferredLibrary)?"":" disabled")?> onclick="$('#holdFooter').css('display', 'none');$('#loadingFooter').css('display', 'block');">Okay</button>
    </form>
  </div>
  <div id="loadingFooter" style="display:none;padding:9px;color:#3d3d3d">
    <span><i class="fa fa-spinner"></i></span>
    <span>&nbsp;Loading...</span>
  </div>

  <script type="text/javascript">
    function SelectPickupLocation(chosenID) {
      var currentID = $('input[name="gatheredDetails[pickUpLocation]"]').val();
      $('i[name="check-' + currentID + '"]').css("color","#fff");
      $('input[name="gatheredDetails[pickUpLocation]"]').val(chosenID);
      $('i[name="check-' + chosenID + '"]').css("color","");
    }

    function ProcessHoldForm() {
      Lightbox.addFormHandler('placeHold', null);
      $('form[name="placeHold"]').attr("action", Lightbox.lastURL);
      $('form[name="placeHold"]').get(0).submit();
      return false;
    }

    Lightbox.addFormHandler('placeHold', ProcessHoldForm);
  </script>
</div>
