<h2><?=$this->transEsc("Downloadable Formats")?></h2>
<div>
  <div class="EIN-m-12 lightboxText">Select one of the format types below to download.  Please note that only one format may be downloaded for each checkout of a title.  If you have already downloaded a particular format of this title, other formats may be unavailable.</div>
  <div class="EIN-m-12">
    <br>
    <table style="margin-left:auto;margin-right:auto">
      <? foreach($this->driver->getFormats() as $format): ?>
        <? if( !in_array($format, ["OverDrive Read", "OverDrive Listen"]) ): ?>
          <? 
            $downloadId = null;
            foreach($this->downloadFormats as $download):
              if($format == $download["name"]):
                $downloadId = $download["id"];
              endif;
            endforeach;
          ?>
          <tr>
            <td style="padding:5px"><span class="formatTag"><?=$format?></span></td>	
            <td class="lightboxText" style="padding:5px">
              <?=($downloadId?("<a href=\"" . ($this->recordLink()->getActionUrl($this->driver, 'OverdriveDownload') . "?formatType=" . $downloadId . ($this->formatLocked?"":"&lockIn=true")) . "\" id=\"format-" . $downloadId ."\" target=\"" . (($downloadId=="periodicals-nook")?"_self":"loginFrame") . "\">"):"")?>
                <button class="btn-default"<?=($downloadId?"":" disabled")?>>Download</button>
              <?=($downloadId?"</a>":"")?>
            </td>
            <td class="lightboxText" style="padding:5px"><span class="<?=($downloadId?"availableTag":"unavailableTag")?>"><?=($downloadId?("<i class=\"fa fa-check\"></i>".($this->formatLocked?"Locked In":"Available")):"Unavailable")?></span></td>
          </tr>
        <? endif; ?>
      <? endforeach; ?>
    </table>
    <br>
  </div>
  <img src="/vufind/themes/truefit/images/icons/overdrive.png" style="float:left;padding-right:20px">
  <div class="EIN-m-12 lightboxText">
    This title requires the <a href="http://www.overdrive.com/software/omc/" target="_blank">OverDrive&#0169; Media Console&#0153;</a> for use. If you do not already have the OverDrive Media Console, you may download it <a href="http://www.overdrive.com/software/omc/" target="_blank">here</a>.
  </div>
  <br>
  <div class="EIN-m-12 lightboxText">
    Need help transferring a title to your device or want to know whether or not your device is compatible with a particular format? Click <a href="http://help.overdrive.com/" target="_blank">here</a> for more information.
  </div>
</div>
<div class="modal-footer">
  <button class="btn-default btn-wide" data-dismiss="modal">Close</button>
</div>
<? if( $downloadId == "video-streaming" ): ?>
  <script type="text/javascript">
    $( function() { $('#format-video-streaming')[0].click(); Lightbox.close(); } );
  </script>
<? endif; ?>
