<?=$this->flashmessages(false)?>
<h2>Select Item</h2>
<div class="hold-form">
  <table class="pickupLocationTable">
    <? if( count($this->availableHoldings) > 0): ?>
      <tr><td colspan="3" class="modalSubheading center">Holdable</td></tr>
      <tr>
        <td class="modalSubheading">Location</td>
        <td class="modalSubheading">Volume</td>
        <td class="modalSubheading">Status</td>
      </tr>
      <? foreach ($this->availableHoldings as $item): ?>
        <tr>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocation" onmouseover="HighlightRow(this, true);" onmouseout="HighlightRow(this, false);" onclick="return SelectItem('<?=$this->escapeHtmlAttr(".i" . $item["itemId"] . "a")?>');"><?=$item["location"]?></button></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocation" onmouseover="HighlightRow(this, true);" onmouseout="HighlightRow(this, false);" onclick="return SelectItem('<?=$this->escapeHtmlAttr(".i" . $item["itemId"] . "a")?>');"><?=$item["number"]?></button></td>
          <td><button class="btn-dropdown btn-standardDropdown btn-pickupLocation" onmouseover="HighlightRow(this, true);" onmouseout="HighlightRow(this, false);" onclick="return SelectItem('<?=$this->escapeHtmlAttr(".i" . $item["itemId"] . "a")?>');"><?=$item["displayStatus"]?></button></td>
        </tr>
      <? endforeach; ?>
    <? elseif(count($this->unavailableHoldings) > 0): ?>
      <tr><td colspan="3" class="messageWarning center">No holdable items</td></tr>
    <? endif; ?>
    <? if( (count($this->unavailableHoldings) > 0) ): ?>
      <tr><td colspan="3"><div class="modal-break"></div></td></tr>
    <? endif; ?>
    <? if( count($this->unavailableHoldings) > 0): ?>
      <tr><td colspan="3" class="modalSubheading center">Not Holdable</td></tr>
      <tr>
        <td class="modalSubheading">Location</td>
        <td class="modalSubheading">Volume</td>
        <td class="modalSubheading">Status</td>
      </tr>
      <? foreach ($this->unavailableHoldings as $item): ?>
        <tr>
          <td><span class="btn-pickupLocation"><?=$item["location"]?></span></td>
          <td><span class="btn-pickupLocation"><?=$item["number"]?></span></td>
          <td><span class="btn-pickupLocation"><?=(($item["displayStatus"]=="AVAILABLE") ? ((strpos($item["callnumber"],"<br>NO REQUESTS") === false) ? "IT'S HERE" : "NO REQUESTS") : $item["displayStatus"])?></span></td>
        </tr>
      <? endforeach; ?>
    <? endif; ?>
  </table>
</div>
<div class="modal-footer">
  <div id="holdFooter">
    <button class="btn-alternate btn-wide" onclick="$('#modalClose').click()">Cancel</button>
  </div>
  <div id="loadingFooter" style="display:none;padding:9px;color:#3d3d3d">
    <span><i class="fa fa-spinner"></i></span>
    <span>&nbsp;Loading...</span>
  </div>

  <script type="text/javascript">
    function HighlightRow(item, highlight) {
      if(highlight) {
        $(item).parents('tr').addClass("hovered");
        $(item).parents('tr').find('button').addClass("hovered");
      } else {
        $(item).parents('tr').removeClass("hovered");
        $(item).parents('tr').find('button').removeClass("hovered");
      }
    }

    function SelectItem(chosenID) {
      Lightbox.get('Record', 'Hold', {'id':'<?=$this->id?>','hashKey':'<?=$this->hashKey?>'}, {'gatheredDetails':{'itemId':chosenID}});
    }
  </script>
</div>
