<hr/>
<div class="row footer">
  <table class="footer">
    <tr><td>&nbsp;</td></tr>
    <tr><td>
      <a href="http://radworkshere.org" target="_blank"><img src="/vufind/themes/bootstrap3/images/einetwork/RADLogo.png" class="RADLogo"></a>
      <a href="http://www.einetwork.net" target="_blank"><img src="/vufind/themes/bootstrap3/images/einetwork/EINLogo.png" class="EINLogo gap"></a>
    </td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>
      Library Catalog is a service of eiNetwork, a collaboration of the <a href="http://www.aclalibraries.org" target="_blank">Allegheny County Library Association</a> and <a href="http://www.carnegielibrary.org" target="_blank">Carnegie Library of Pittsburgh</a>.
    </td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>
      <a href="#" target="_blank">Locations</a>
      <a href="#" target="_blank" class="gap">Help</a>
      <a href="http://www.einetwork.net/ils/requests/acquire_web_ngc.php" target="_blank" class="gap">Suggest a Purchase</a>
    </td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>&copy;eiNetwork</td></tr>
    <tr><td>&nbsp;</td></tr>
  </div>
</div>
