<?
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li class="active">' . $this->transEsc('History') . '</li>';
?>

<?=$this->flashmessages()?>

<div class="EIN-col-m-12 padded">
  <? if (!empty($this->saved)): ?>
    <h1 class="pageTitle"><?=$this->transEsc("history_saved_searches")?></h1>
    <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true));?>
    <div class="EIN-col-m-12" style="height:20px"></div>
  <? endif; ?>

  <h1 class="pageTitle"><?=$this->transEsc("history_recent_searches")?></h1>
  <? if (!empty($this->unsaved)): ?>
    <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false));?>
    <div class="EIN-col-m-12 center">
      <div class="EIN-col-m-12" style="height:20px"></div>
      <a href="?purge=true"><button class="btn-default btn-wide"><?=$this->transEsc("history_purge")?></button></a>
      <div class="EIN-col-m-12" style="height:20px"></div>
    </div>
  <? else: ?>
    <div class="EIN-col-m-12" style="height:20px"></div>
    <div class="EIN-col-m-12 center"><?=$this->transEsc("history_no_searches")?></div>
    <div class="EIN-col-m-12" style="height:20px"></div>
  <? endif; ?>
</div>