<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
  <?=$this->flashmessages()?>
  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <?=$this->render("search/splashsearchbox.phtml")?>
</div>
<script type="text/javascript">
  function MoveSliderLeft(slider) {
    var leftBtn = slider.children[0].children[0];
    var rightBtn = slider.children[2].children[0];
    var sliderTable = slider.children[1].children[0];
    var childTDs = $(sliderTable).find("td");
    for( var i=slider.showIndex; i<slider.showIndex + 3 && i<childTDs.length; i++) {
      childTDs.eq(i).addClass("newestItemHidden").removeClass("newestItem");
    }
    slider.showIndex -= 3
    for( var i=slider.showIndex; i<slider.showIndex + 3; i++) {
      childTDs.eq(i).addClass("newestItem").removeClass("newestItemHidden");
    }
    leftBtn.disabled = (slider.showIndex == 0);
    rightBtn.disabled = false;
  }

  function MoveSliderRight(slider) {
    if( !slider.hasOwnProperty("showIndex") ) {
      slider.showIndex = 0;
    }

    var leftBtn = slider.children[0].children[0];
    var rightBtn = slider.children[2].children[0];
    var sliderTable = slider.children[1].children[0];
    var childTDs = $(sliderTable).find("td");
    for( var i=slider.showIndex; i<slider.showIndex + 3; i++) {
      childTDs.eq(i).addClass("newestItemHidden").removeClass("newestItem");
    }
    slider.showIndex += 3
    for( var i=slider.showIndex; i<slider.showIndex + 3 && i<childTDs.length; i++) {
      childTDs.eq(i).addClass("newestItem").removeClass("newestItemHidden");
    }
    leftBtn.disabled = false;
    rightBtn.disabled = (slider.showIndex + 3) >= childTDs.length;
  }

  jQuery(document).ready(function() {
    // if they're trying to show the text notices help, give it to them
    if( window.location.href.toLowerCase().indexOf("/myresearch/smshelp") != -1 ) {
      Lightbox.addOpenAction( function() { 
        $('#modal').on('shown.bs.modal', function() { location.hash = "#section3-6" });
      } );
      Lightbox.get('Help','Home');
    }
    // if they're trying to show the pin reset dialog, give it to them
    else if( window.location.href.toLowerCase().indexOf("/myresearch/pinreset") != -1 ) {
      Lightbox.addOpenAction( function() { 
        $('#modal').on('shown.bs.modal', function() { ToggleLoginModal(document.getElementById('loginModalReset')); });
      } );
      Lightbox.get('MyResearch','Login');
    }
    // if they're trying to show the register dialog, give it to them
    else if( window.location.href.toLowerCase().indexOf("/myresearch/getcard") != -1 ) {
      Lightbox.addOpenAction( function() { 
        $('#modal').on('shown.bs.modal', function() { ToggleLoginModal(document.getElementById('loginModalRegister')); });
      } );
      Lightbox.get('MyResearch','Login');
    }
  } );
</script>
<div class="splashNewest">
  <? if(is_object($this->BookResults) && count($BookResults = $this->BookResults->results->getResults()) > 0): ?>
    <h1 class="newestHeader">Newest Print Books</h1>
    <table style="width:100%">
      <tr>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderLeft(this.parentElement.parentElement)" disabled><i class="fa fa-chevron-left"></i></button>
        </td>
        <td style="width:76%" class="sliderWindow">
          <table style="width:100%"><tr>
          <? $count = 0; foreach ($BookResults as $entry): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"><a href="<?=$this->recordLink()->getUrl($entry)?>"><div class="newestEntryLev1" style="width:100%; margin:0"><div class="newestEntryLev2"><div class="newestEntryLev3">
              <img class="newestEntryImg" src="<?= $this->escapeHtmlAttr($this->record($entry)->getThumbnail()) ?>" />
            </div></div></div></a></td>
          <? endforeach ?>
          <? while( $count % 3 ): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"></td>
          <? endwhile; ?>
          </tr></table>
        </td>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderRight(this.parentElement.parentElement)"<?= (($this->BookResults->results->getResultTotal() <= 3) ? " disabled" : "") ?>><i class="fa fa-chevron-right"></i></button>
        </td>
      </tr>
    </table>
  <? endif; ?>
  <? if(is_object($this->DVDResults) && count($DVDResults = $this->DVDResults->results->getResults()) > 0): ?>
    <h1 class="newestHeader">Newest DVDs</h1>
    <table style="width:100%">
      <tr>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderLeft(this.parentElement.parentElement)" disabled><i class="fa fa-chevron-left"></i></button>
        </td>
        <td style="width:76%" class="sliderWindow">
          <table style="width:100%"><tr>
          <? $count = 0; foreach ($DVDResults as $entry): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"><a href="<?=$this->recordLink()->getUrl($entry)?>"><div class="newestEntryLev1" style="width:100%; margin:0"><div class="newestEntryLev2"><div class="newestEntryLev3">
              <img class="newestEntryImg" src="<?= $this->escapeHtmlAttr($this->record($entry)->getThumbnail()) ?>" />
            </div></div></div></a></td>
          <? endforeach ?>
          <? while( $count % 3 ): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"></td>
          <? endwhile; ?>
          </tr></table>
        </td>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderRight(this.parentElement.parentElement)"<?= (($this->DVDResults->results->getResultTotal() <= 3) ? " disabled" : "") ?>><i class="fa fa-chevron-right"></i></button>
        </td>
      </tr>
    </table>
  <? endif; ?>
  <? if(is_object($this->eBookResults) && count($ebookResults = $this->eBookResults->results->getResults()) > 0): ?>
    <h1 class="newestHeader">Newest eBooks</h1>
    <table style="width:100%">
      <tr>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderLeft(this.parentElement.parentElement)" disabled><i class="fa fa-chevron-left"></i></button>
        </td>
        <td style="width:76%" class="sliderWindow">
          <table style="width:100%"><tr>
          <? $count = 0; foreach ($ebookResults as $entry): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"><a href="<?=$this->recordLink()->getUrl($entry)?>"><div class="newestEntryLev1" style="width:100%; margin:0"><div class="newestEntryLev2"><div class="newestEntryLev3">
              <img class="newestEntryImg" src="<?= $this->escapeHtmlAttr($this->record($entry)->getThumbnail()) ?>" />
            </div></div></div></a></td>
          <? endforeach ?>
          <? while( $count % 3 ): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"></td>
          <? endwhile; ?>
          </tr></table>
        </td>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderRight(this.parentElement.parentElement)"<?= (($this->eBookResults->results->getResultTotal() <= 3) ? " disabled" : "") ?>><i class="fa fa-chevron-right"></i></button>
        </td>
      </tr>
    </table>
  <? endif; ?>
  <? if(false && is_object($this->CDResults) && count($CDResults = $this->CDResults->results->getResults()) > 0): ?>
    <h1 class="newestHeader">Newest Music CDs</h1>
    <table style="width:100%">
      <tr>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderLeft(this.parentElement.parentElement)" disabled><i class="fa fa-chevron-left"></i></button>
        </td>
        <td style="width:76%" class="sliderWindow">
          <table style="width:100%"><tr>
          <? $count = 0; foreach ($CDResults as $entry): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"><a href="<?=$this->recordLink()->getUrl($entry)?>"><div class="newestEntryLev1" style="width:100%; margin:0"><div class="newestEntryLev2"><div class="newestEntryLev3">
              <img class="newestEntryImg" src="<?= $this->escapeHtmlAttr($this->record($entry)->getThumbnail()) ?>" />
            </div></div></div></a></td>
          <? endforeach ?>
          <? while( $count % 3 ): ?>
            <td class="newestItem<? echo ($count < 3) ? "" : "Hidden"; $count++; ?>"></td>
          <? endwhile; ?>
          </tr></table>
        </td>
        <td style="width:12%">
          <button class="sliderButton" onclick="MoveSliderRight(this.parentElement.parentElement)"<?= (($this->CDResults->results->getResultTotal() <= 3) ? " disabled" : "") ?>><i class="fa fa-chevron-right"></i></button>
        </td>
      </tr>
    </table>
  <? endif; ?>
  <h1 class="newestHeader">Additional Resources</h1>
  <table style="width:100%">
    <tr>
      <td class="additionalResourceHolder EIN-col-m-6 EIN-col-t-3"><a href="http://bookdb.nextgoodbook.com/signup/pl/f485432415b23a8962922e0b2d198227" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <img src="/themes/truefit/images/icons/selectreads-block.png">
        </td></tr></tbody></table></div>
      </a></td>
      <td class="additionalResourceHolder EIN-col-m-6 EIN-col-t-3"><a href="http://nextgoodbook.com/newsletter/landing/l/f485432415b23a8962922e0b2d198227/c/1000" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <img src="/themes/truefit/images/icons/New-Book-Alerts.jpg">
        </td></tr></tbody></table></div>
      </a></td>
      <td class="additionalResourceHolder EIN-hide-m EIN-col-t-3"><a href="http://authordb.nextgoodbook.com/landing/l/f485432415b23a8962922e0b2d198227" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <img src="/themes/truefit/images/icons/authorchecklogo.png">
        </td></tr></tbody></table></div>
      </a></td>
      <td class="additionalResourceHolder EIN-hide-m EIN-col-t-3"><a href="http://search.ebscohost.com/login.aspx?authtype=cpid&amp;custid=s4663075&amp;profile=novelist" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <img src="/themes/truefit/images/icons/novelist_button.gif">
        </td></tr></tbody></table></div>
      </a></td>
    </tr>
    <tr class="EIN-hide-t EIN-hide">
      <td class="additionalResourceHolder EIN-col-m-6"><a href="http://authordb.nextgoodbook.com/landing/l/f485432415b23a8962922e0b2d198227" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <img src="/themes/truefit/images/icons/authorchecklogo.png">
        </td></tr></tbody></table></div>
      </a></td>
      <td class="additionalResourceHolder EIN-col-m-6"><a href="http://search.ebscohost.com/login.aspx?authtype=cpid&amp;custid=s4663075&amp;profile=novelist" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <img src="/themes/truefit/images/icons/novelist_button.gif">
        </td></tr></tbody></table></div>
      </a></td>
    </tr>
    <tr>
      <td class="EIN-hide-m EIN-col-t-3 EIN-col-3">&nbsp;</td>
      <td class="additionalResourceHolder EIN-col-m-6 EIN-col-t-3 EIN-col-3"><a href="http://erec.einetwork.net" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <span>Databases and Articles</span>
        </td></tr></tbody></table></div>
      </a></td>
      <td class="additionalResourceHolder EIN-col-m-6 EIN-col-t-3 EIN-col-3"><a href="http://illiad.carnegielibrary.org/illiad/logon.html" target="_blank">
        <div class="additionalResource"><table style="width:100%;height:100%"><tbody><tr><td>
          <span>Interlibrary Loan</span>
        </td></tr></tbody></table></div>
      </a></td>
      <td class="EIN-hide-m EIN-col-t-3 EIN-col-3">&nbsp;</td>
    </tr>
  </table>
</div>
