<!--  <div class="well well-lg clearfix"> -->
<div class="splashSearchOutline">
<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
?>
  <form role="search" method="get" action="<?=$this->url($basicSearch)?>" name="splashSearchForm" id="LCsearchForm" autocomplete="off">
    <?= $this->render('search/searchTabs'); ?>
    <table onMouseOver="hideSearchBoxTypeLabel()">
      <tr>
        <td style="width:100%">
          <div style="padding:0 5px">
            <span class="sr-only">Search for:</span>
            <input class="form-control splashSearchBox search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?> initialSearch searchBox" type="text" name="lookfor" value="Search For..." onfocus="SearchFocus(this);" onfocusout="SearchFocusOut(this);"/>
          </div>
        </td>
        <td>
          <button type="submit" class="btn btn-noBorderAlternate floatR"><span class="sr-only">Search</span><i class="fa fa-search"></i></button>
        </td>
        <td><span id="searchBoxTypeLabel" style="color:#3f51b5; font-weight:700; white-space:nowrap"><?=$this->escapeHtmlAttr($handlers[0]['value'])?></span></td>
        <td>
          <button class="btn btn-noBorderAlternate floatR" data-toggle="dropdown" data-target="#searchBoxDropdown" onclick="mostRecentSearchBtn = this; moveButtons();"><span class="sr-only">Search Options</span><i class="fa fa-cog" style="font-size:18px; margin:3px 0px"></i></button>
        </td>
      </tr>
    </table>
    <input type="hidden" class="searchTypeInput" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
    <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
      <?
      $selectedShards = isset($this->selectedShards)
          ? $this->selectedShards : $options->getDefaultSelectedShards();
      ?>
      <br />
      <? foreach ($shards as $shard => $val): ?>
        <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
      <? endforeach; ?>
    <? endif; ?>
    <?
      $filterDetails = $this->searchbox()->getFilterDetails(
          isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
          isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
      );
    ?>
    <input type="hidden" class="searchRetainFilters" name="retainFilters" value="true" />
    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
      <? $defaultFilterState = ($options->getRetainFilterSetting() && $this->ils()->getDriver()->getSessionVar("retainFilters")) ? ' checked="checked"' : ''; ?>
      <div class="hidden">
        <? foreach ($filterDetails as $current): ?>
          <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
          <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
        <? endforeach; ?>
        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
          <!-- this is a hidden element that flags whether or not default filters have been applied;
               it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
          <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
        <? endif; ?>
      </div>
    <? endif; ?>
    <?
      /* Show hidden field for active search class when in combined handler mode. */
      if ($this->searchbox()->combinedHandlersActive()) {
        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
      }
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
      }
    ?>
  </form>
  <script type="text/javascript">
    $("#searchForm_lookfor").focus();

    function SearchFocus(elem) {
      $(elem).parent().css({"background-color":"#ededed"});
      $(".initialSearch").typeahead('val', '');
      $(".initialSearch").removeClass("initialSearch");
    }

    function SearchFocusOut(elem) {
      $(elem).parent().css({"background-color":"#fff"});
    }

    // submit the login on enter press
    $("#LCsearchForm input").keypress(function(event) {
      if (event.which == 13) {
        event.preventDefault();
        $('#LCsearchForm').submit();
      }
    });
  </script>
</div>
