<?
  // Set up convenience variables:
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $record = $this->record($this->driver);
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="EIN-col-m-12">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $record->getThumbnail('medium'); $largeThumb = $record->getThumbnail('large'); ?>
      <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $record->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$record->getPreviews()?>
  </div>

  <div class="EIN-col-m-12 padded">
    <h1 property="name" class="itemTitle"><?=$this->escapeHtml(trim($this->driver->getShortTitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getSubtitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getTitleSection(),"\0\t\n\x0B\r /"))?></h1>

    <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
    <? if (isset($authors['main']) && !empty($authors['main'])): ?>
      <h4 property="author" class="itemAuthor">by <a href="<?=$record->getLink('author', $authors['main'])?>" class="authorLink"><?=$this->escapeHtml($authors['main'])?></a></h4>
    <? endif; ?>

    <p class="titleInfoLine">
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <? foreach( $formats as $thisFormat ): ?>
          <span class="formatTag"><?=$thisFormat?></span>
        <? endforeach; ?>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
        <? foreach ($publications as $field): ?>
          <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
            <span property="publicationDate" class="publishDate"><?=$this->escapeHtml($pubDate)?></span>
          <? endif; ?>
        <? endforeach; ?>
      <? endif; ?>
    </p>

    <p class="titleInfoLine">
      <? $totalCopies = 0; $availableCopies = 0; ?>
      <? foreach($this->holdings as $entry): ?>
        <? foreach($entry["items"] as $item): ?>
          <? $totalCopies++; $availableCopies += ($item["availability"]); ?>
        <? endforeach; ?>
      <? endforeach; ?>
      <? $green = (($totalCopies > 0) && ($availableCopies > 0)); ?>
      <span class="<?=($green ? "availableTag" : "unavailableTag")?>"><?=($green ? '<i class="fa fa-check"></i>Available' : "Unavailable")?></span>
      <span class="<?=($green ? "availableCopyText" : "unavailableCopyText")?>"><?=((($totalCopies > 0) ? ($availableCopies . " of ") : "") . $totalCopies . " cop" . (($totalCopies == 1) ? "y" : "ies"))?></span>
    </p>

    <?
      if($user):
        $holdArgs = "'Record','Hold'," . $this->holdArgs;
        $saveClick = " onClick=\"Lightbox.get('Record','Save'," . $this->saveArgs . ")\"";
        $saveClick = " data-toggle=\"dropdown\" data-target=\"#listButtonDropdown\"";
      else:
        $holdArgs = "'MyResearch','Login'";
        $saveClick = " onClick=\"Lightbox.get('MyResearch','Login')\"";
      endif;

      $holdLabel = ($this->canHold ? "Hold" : ($this->isTitleHeld ? "Holding" : "Unable to Hold"));
    ?>
    <p class="titleInfoLine">
      <table class="sideBySideButtons"><tr>
        <td style="width:50%"><button class="btn-default leftButton" onClick="Lightbox.get(<?=$holdArgs?>)"<?=($this->canHold?"":" disabled")?>><?=$holdLabel?></button></td>
        <td style="width:50%">
          <button class="btn-default rightButton"<?=$saveClick?>><?=($this->hasOnList)?"Manage Lists":"Add to List"?><?=($user?"<i class=\"fa fa-caret-down\"></i>":"")?></button>
          <div class="EIN-col-m-12 dropdown" id="listButtonDropdown">
            <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
              <? foreach($this->myLists as $list): ?>
                <li>
                  <? if($list->contains($this->driver->getResourceSource()."|".$this->driver->getUniqueID())): ?>
                    <form method="post" action="<?=$this->url('userList', array('id' => $list->id))?>">
                      <input type="hidden" name="confirm" value="1">
                      <input type="hidden" name="delete" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="returnBibID" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown"><i class="fa fa-check greenCheck"></i><?=$list->title?></button>
                    </form>
                  <? else: ?>
                    <form method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>">
                      <input type="hidden" name="submit" value="1">
                      <input type="hidden" name="id" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown"><?=$list->title?></button>
                    </form>
                  <? endif; ?>
                </li>
              <? endforeach; ?>
              <li><button class="btn-dropdown btn-standardDropdown" onclick="Lightbox.get('MyResearch','EditList',{'id':'NEW','recordId':'<?=$this->driver->getUniqueID()?>'})">New list...</button></li>
              <? if ($this->hasOnList): ?>
                <hr class="stretchHR">
                <li><span class="modalNote">Click a non-checked list to add this title.  Click a checked list to remove this title.</span></li>
              <? endif; ?>
            </ul>
          </div>
        </td>
      </tr></table>
    </p>

    <p class="titleInfoLine">
      <div class="panel-group" id="detailsAccordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details1" class="collapsed">Availability Details<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details1" class="panel-collapse collapse">
            <div class="panel-body">
              <? if( $availableCopies > 0): ?>
                <h6 class="accordionSubheading">Available (<?=$availableCopies?>)</h6>
                <table class="EIN-col-m-12">
                  <tr class="availabilityHeaderRow">
                    <td class="EIN-col-m-4">Location</td>
                    <td class="EIN-col-m-4">Collection</td>
                    <td class="EIN-col-m-4">Call #</td>
                  </tr>
                  <? foreach($this->holdings as $thisHolding): ?>
                    <? foreach($thisHolding['items'] as $item): ?>
                      <? if($item['availability']): ?>
                        <tr class="availabilityRow">
                          <td class="EIN-col-m-4"><?=$item['branchName']?></td>
                          <td class="EIN-col-m-4"><?=$item['shelvingLocation']?></td>
                          <td class="EIN-col-m-4"><?=$item['callnumber']?></td>
                        </tr>
                      <? endif; ?>
                    <? endforeach; ?>
                  <? endforeach; ?>
                </table>
              <? endif; ?>
              <? if( $totalCopies > 0 && $totalCopies != $availableCopies && $availableCopies > 0): ?>
                <span class="accordionGap">&nbsp;</span>
              <? endif; ?>
              <? if( $totalCopies > 0 && $totalCopies != $availableCopies ): ?>
                <h6 class="accordionSubheading">Unavailable (<?=($totalCopies - $availableCopies)?>)</h6>
                <table class="EIN-col-m-12">
                  <tr class="availabilityHeaderRow">
                    <td class="EIN-col-m-4">Location</td>
                    <td class="EIN-col-m-4">Collection</td>
                    <td class="EIN-col-m-4">Status</td>
                  </tr>
                  <? foreach($this->holdings as $thisHolding): ?>
                    <? foreach($thisHolding['items'] as $item): ?>
                      <? if(!$item['availability']): ?>
                        <tr class="availabilityRow">
                          <td class="EIN-col-m-4"><?=$item['branchName']?></td>
                          <td class="EIN-col-m-4"><?=$item['shelvingLocation']?></td>
                          <td class="EIN-col-m-4"><?=$item['displayStatus']?></td>
                        </tr>
                      <? endif; ?>
                    <? endforeach; ?>
                  <? endforeach; ?>
                </table>
              <? endif; ?>
            </div>
          </div>
        </div>
        <div class="panel panel-default" style="display:none">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details2" class="collapsed">Other Formats & Languages<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details2" class="panel-collapse collapse">
            <div class="panel-body">
              <span>Something</span>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details3" class="collapsed">Details<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details3" class="panel-collapse collapse">
            <div class="panel-body">
              <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>              
              <? if ($summary): ?>
                <h6 class="accordionSubheading">Summary</h6>
                <span class="accordionParagraph"><?=$summary?></span><br>
              <? endif; ?>
              <? if( isset($this->tabs['Reviews']) ): ?>
                <? $reviewSources = $this->tabs['Reviews']->getContent($this->driver->getCleanISBN()); ?>
                <? if( count($reviewSources) > 0 ): ?>
                  <h6 class="accordionSubheading accordionGap">Published Reviews</h6>
                  <? foreach( $reviewSources as $reviews ): ?>
                    <? foreach( $reviews as $review ): ?>
                      <span class="reviewSource"><?=$review['Source']?>: </span>
                      <span class="accordionParagraph">"<?=$review['Content']?>"</span><br>
                      <span class="EIN-col-m-12 reviewCopyright"><?=$review['Copyright']?></span><br>
                    <? endforeach; ?>
                  <? endforeach; ?>
                <? endif; ?>
              <? endif; ?>
              <h6 class="accordionSubheading accordionGap">Colophon</h6>
              <table class="EIN-col-m-12 accordionTable">
                <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Publisher')?></td>
                    <td><? foreach($publications as $thisPublication): ?>
                      <span><?= $this->escapeHtml($thisPublication->getPlace()) . $this->escapeHtml($thisPublication->getName()) . $this->escapeHtml($thisPublication->getDate()) ?></span><br>
                    <? endforeach; ?></td>
                  </tr>
                <? endif; ?>
                <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Edition')?></td>
                    <td><?=$this->escapeHtml($edition)?></td>
                  </tr>
                <? endif; ?>
                <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Contributors')?></td>
                    <td>
                      <? foreach ($authors['secondary'] as $field): ?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><br><? endforeach; ?>
                    </td>
                  </tr>
                <? endif; ?>
                <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Language')?></td>
                    <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
                  </tr>
                <? endif; ?>
                <? $marcDesc = $this->driver->getFormattedMarcDetails(300,['|abc']); if (!empty($marcDesc)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Description')?></td>
                    <td><?=$this->escapeHtml($marcDesc[0][0])?></td>
                  </tr>
                <? endif; ?>
                <? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('ISBN')?></td>
                    <td><? foreach ($isbns as $isbn): ?><?= $this->escapeHtml($isbn)?><br/><? endforeach; ?></td>
                  </tr>
                <? endif; ?>
              </table>
            </div>
          </div>
        </div>
      </div>
    </p>
  </div>
</div>
