<?
  // Set up convenience variables:
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $record = $this->record($this->driver);
  $isOverDrive = false;
  $isOneClick = false;
  $hasVolumes = false;
  $holdableCopyHere = false;
  $onOrder = false;
  foreach($this->holdings as $entry):
    foreach($entry["items"] as $item):
      if( isset($item["isOverDrive"]) && $item["isOverDrive"] ):
        $isOverDrive = true;
      endif;
      if( isset($item["number"]) && $item["number"]):
        $hasVolumes = true;
      endif;
      if( isset($item["status"]) && (($item["status"]=="order") || ($item["status"]=="i")) ):
        $onOrder = true;
      endif;      
    endforeach;
  endforeach;
  $urls = $this->driver->getURLs();
  foreach($urls as $key => $thisUrl):
    if( $isOverDrive && (strpos($thisUrl["url"], "http://excerpts.contentreserve.com") === false) ):
      unset($urls[$key]);
    elseif( strpos($thisUrl["url"], "http://www.carnegielibrary.org/research/music/pittsburgh/pghlps.html") !== false ):
      unset($urls[$key]);
    elseif( strpos($thisUrl["url"], "http://carnegielbyofpittpa.oneclickdigital.com") !== false ):
      $isOneClick = true;
    endif;
  endforeach;
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="EIN-col-m-12 EIN-col-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $largeThumb = $record->getThumbnail('large'); ?>
      <? if ($largeThumb): ?>
        <a href="<?=$this->escapeHtmlAttr($largeThumb)?>">
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcoverdetails" src="<?=$this->escapeHtmlAttr($largeThumb);?>"/>
        </a>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcoverdetails" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $record->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$record->getPreviews()?>
  </div>

  <div class="EIN-col-m-12 EIN-col-9 padded">
    <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
      <h1 property="name" class="itemTitle"><?=$this->escapeHtml($isOverDrive ? trim($this->driver->getTitle(),"\0\t\n\x0B\r /") : (trim($this->driver->getShortTitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getSubtitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getTitleSection(),"\0\t\n\x0B\r /")))?></h1>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <h4 property="author" class="itemAuthor">by <a href="<?=$record->getLink('author', $authors['main'])?>" class="authorLink"><?=$this->escapeHtml($authors['main'])?></a></h4>
      <? endif; ?>

      <table>
        <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
          <? $firstTime = true; foreach( $formats as $thisFormat ): ?>
            <tr>
              <td class="EIN-hide-m itemDetailCategory"><?=($firstTime?"Format:":"&nbsp;")?></td>
              <td style="padding-bottom:5px">
                <span class="formatTag"><?=$thisFormat?></span>

                <? if( $firstTime ): ?>
                  <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                    <? foreach ($publications as $field): ?>
                      <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                        <span property="publicationDate" class="publishDate"><?=$this->escapeHtml($pubDate)?></span>
                      <? endif; ?>
                    <? endforeach; ?>
                  <? endif; ?>
                  <? $firstTime = false; ?>
                <? endif; ?>
              </td>
            </tr>
          <? endforeach; ?>
        <? endif; ?>

        <? if( isset($this->holdings["CHECKIN_RECORDS"]) ): ?>
          <? $serialCheckinRecord = false; ?>
          <? foreach( $this->holdings["CHECKIN_RECORDS"]["items"][0]["checkinRecords"] as $checkinLoc ): ?>
            <? if( $this->currentLocation && in_array($this->currentLocation["code"], $checkinLoc["branchCode"]) ): ?>
              <? $heldHere = $checkinLoc; ?>
            <? endif; ?>
            <? $serialCheckinRecord |= isset($checkinLoc["libHas"]); ?>
          <? endforeach; ?>
          <? if( $serialCheckinRecord ): ?>
            <tr>
              <td class="EIN-hide-m itemDetailCategory">Availability:</td>
              <td style="padding-bottom:5px">
                <span class="availableTag"><i class="fa fa-check"></i>In Library Only</span>
                <span class="availableCopyText"><?=count($this->holdings["CHECKIN_RECORDS"]["items"][0]["checkinRecords"])?> location<?=((count($this->holdings["CHECKIN_RECORDS"]["items"][0]["checkinRecords"]) != 1) ? "s" : "")?></span>
                <? if( isset($heldHere) ): ?>
                  <div class="availableCopyText">It's here at <?=$heldHere['location']?></div>
                <? endif; ?>
              </td>
            </tr>
          <? endif; ?>
        <? endif; ?>
        <? $totalCopies = 0; $availableCopies = 0; $noncirculatingCopies = 0; ?>
        <? foreach($this->holdings as $entry): ?>
          <? foreach($entry["items"] as $item): ?>
            <? if( isset($item["copiesOwned"])) : ?>
              <? $totalCopies += ($item["copiesOwned"]); ?>
            <? else: ?>
              <? $totalCopies++; ?>
            <? endif; ?>
            <? if( isset($item["isOverDrive"]) && $item["isOverDrive"] ): ?>
              <? $availableCopies += ($item["copiesAvailable"]); ?>
            <? else: ?>
              <? $availableCopies += $item["availability"]; ?>
              <? $noncirculatingCopies += ($item["status"] == "o"); ?>
              <? if(!isset($itsHere) && $this->currentLocation && $item["availability"] && ($item["branchCode"] == $this->currentLocation["code"])): ?>
                <? $itsHere = $item; ?>
              <? endif; ?>
              <? if(!$holdableCopyHere && $this->currentLocation && $item["availability"] && ($item["branchCode"] == $this->currentLocation["code"]) && ($item["status"] != "o") && ($item["status"] != "order")): ?>
                <? $holdableCopyHere = $item; ?>
              <? endif; ?>
            <? endif; ?>
          <? endforeach; ?>
        <? endforeach; ?>
        <? $alwaysAvailable = $isOverDrive && ($totalCopies == 999999); ?>
        <? $green = $isOneClick || (($totalCopies > 0) && (($availableCopies > 0) || ($onOrder))); ?>
        <? if( !isset($this->holdings["CHECKIN_RECORDS"]) || ($totalCopies > 0) ): ?>
          <tr>
            <td class="EIN-hide-m itemDetailCategory"><?=((isset($this->holdings["CHECKIN_RECORDS"]) && $serialCheckinRecord) ? "" : "Availability:")?></td>
            <td style="padding-bottom:5px">
              <span class="<?=($green ? "availableTag" : "unavailableTag")?>"><?=($green ? ('<i class="fa fa-check"></i>' . (isset($itsHere) ? 'It\'s Here!' : (($availableCopies > 0) ? 'Available' : ($onOrder ? 'On Order' : ($isOneClick ? 'Access Online' : 'Available'))))) : "Unavailable")?></span>
              <? if( $alwaysAvailable ): ?>
                <span class="availableCopyText">Always Available</span>
              <? elseif( $isOneClick ): ?>
                <span class="availableCopyText"></span>
              <? elseif( $onOrder ): ?>
                <span class="availableCopyText"> <?=($totalCopies . " cop" . (($totalCopies == 1) ? "y" : "ies"))?></span>
              <? else: ?>
                <span class="<?=($green ? "availableCopyText" : "unavailableCopyText")?>"><?=((($totalCopies > 0) ? ($availableCopies . " of ") : "") . $totalCopies . " cop" . (($totalCopies == 1) ? "y" : "ies"))?></span>
              <? endif; ?>
              <? if( isset($itsHere) ): ?>
                <div class="availableCopyText"><?=$itsHere['shelvingLocation'] . ((isset($itsHere['shelvingLocation']) && isset($itsHere['callnumber'])) ? "<br>" : "") . $itsHere["callnumber"] . (($itsHere["number"] != null) ? (" " . $itsHere["number"]) : "")?></div>
              <? endif; ?>
            </td>
          </tr>
        <? endif; ?>
        <? if( !empty($urls) ): ?>
          <tr>
            <td class="EIN-hide-m itemDetailCategory">Links:</td>
            <td><span class="accordionParagraph">
              <? foreach($urls as $thisURL): ?>
                <div class="itemURL"><a href="<?=$thisURL["url"]?>" target="_blank"><?=($isOneClick ? 'Download from OneClick' : $thisURL["desc"])?></a></div>
              <? endforeach; ?>
            </span></td>
          </tr>
        <? endif; ?>
      </table>

      <?
        $holdLink = null;
        if($user && $this->isTitleCheckedOut && $isOverDrive):
          $holdClick = " data-toggle=\"dropdown\" data-target=\"#holdButtonDropdown,#holdButtonDropdownMobile\"";
          $saveClick = " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown,#saveButtonDropdownMobile\"";
        else:
          if( $isOverDrive ) {
            $hashKey = json_decode(str_replace("'", "\"", $this->holdArgs))->hashKey;
            $holdLink = $this->recordLink()->getActionUrl($this->driver, (!$this->canHold && $this->canCheckOut) ? "Checkout" : "Hold") . (($hashKey != "") ? ("?hashKey=" . $hashKey) : "");
            $holdClick = " onClick=\"$(this).html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')\"";
          } else {
            $holdClick = " onClick=\"Lightbox.get('Record'," . ((!$this->canHold && $this->canCheckOut) ? ("'Checkout'," . $this->idArgs) : ($hasVolumes ? ("'SelectItem'," . $this->holdArgs) : ("'Hold'," . $this->holdArgs))) . ")\"";
          }
          $saveClick = ($user ? " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown,#saveButtonDropdownMobile\"" : " onClick=\"Lightbox.get('MyResearch','Login',false,{'clearLightbox':true})\"");
        endif;

        $holdLabel = ($this->canHold ? (($holdableCopyHere && !$hasVolumes) ? "It's Here" : "Hold") : ($this->isTitleHeld ? "Holding" : ($this->canCheckOut ? "Check Out" : ($this->isTitleCheckedOut ? "Checked Out" : ($isOverDrive ? "Learn More" : (($this->libraryOnly || isset($this->holdings["CHECKIN_RECORDS"])) ? "In Library Only" : "Unable to Hold"))))));
        if( $this->isTitleCheckedOut && $isOverDrive ):
          $holdLabel .= "<i class=\"fa fa-caret-down\"></i>";
        elseif( $isOverDrive && $holdLabel == "Learn More" ):
          $linkURLs = $this->driver->getURLs();
          $holdClick = " onClick=\"window.open('" . $linkURLs[0]["url"] . "', '_blank');\"";
          $holdLink = null;
        endif;
      ?>
    </div>
    <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4" style="padding:5px 0px 10px">
      <div class="EIN-col-m-6 EIN-col-t-12 EIN-col-12">
        <? if($holdLink != null): ?>
          <a href="<?=$holdLink?>" target="loginFrame">
        <? endif; ?>
        <button class="btn-default leftButton"<?=$holdClick?><?=((($this->canHold && (!$holdableCopyHere || $hasVolumes)) || $this->canCheckOut || $isOverDrive)?"":" disabled")?>><?=$holdLabel?></button>
        <? if($holdLink != null): ?>
          </a>
        <? endif; ?>
        <div class="dropdown EIN-hide-m" id="holdButtonDropdown">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if( $this->ODread && $this->ODread["result"] ): ?>
              <li>
                <a href="<?=$this->ODread["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Read Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->mediaDo && $this->mediaDo["result"] ): ?>
              <li>
                <a href="<?=$this->mediaDo["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Read Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->ODlisten && $this->ODlisten["result"] ): ?>
              <li>
                <a href="<?=$this->ODlisten["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Listen Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->ODwatch && $this->ODwatch["result"] ): ?>
              <li>
                <a href="<?=$this->ODwatch["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Watch Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->downloadFormats && count($this->downloadFormats) > 0 ): ?>
              <?
                $streamingVideo = false;
                $nookPeriodical = false;
                foreach($this->downloadFormats as $thisFormat): 
                  $streamingVideo |= (strval($thisFormat["id"]) == "video-streaming");
                  $nookPeriodical |= (strval($thisFormat["id"]) == "periodicals-nook");
                endforeach;
              ?>
              <li>
                <button class="btn-dropdown btn-standardDropdown" onClick="Lightbox.get('Record','OverdriveDownload',<?=str_replace("}", (",'parentURL':'" . $this->CurrentPath() . "'}"), $this->idArgs)?>)"><?=($streamingVideo?"Watch Now":"Download")?></button>
              </li>
            <? endif; ?>
            <? if( $this->canReturn ): ?>
              <li>
                <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Return')?>" target="loginFrame">
                  <button class="btn-dropdown btn-standardDropdown" onClick="$('.leftButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')">Return</button>
                </a>
              </li>
            <? endif; ?>
          </ul>
        </div>
      </div>
      <div class="EIN-col-m-6 EIN-col-t-12 EIN-col-12">
        <button class="btn-default rightButton"<?=$saveClick?>><?=$this->transEsc("list_manage")?><?=($user?"<i class=\"fa fa-caret-down\"></i>":"")?></button>
        <div class="dropdown EIN-hide-m" id="saveButtonDropdown">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if($this->myLists): ?>
              <? foreach($this->myLists as $list): ?>
                <li>
                  <? if($list->contains($this->driver->getResourceSource()."|".$this->driver->getUniqueID())): ?>
                    <form method="post" action="<?=$this->url('userList', array('id' => $list->id))?>">
                      <input type="hidden" name="confirm" value="1">
                      <input type="hidden" name="delete" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="returnBibID" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown" onClick="$('.rightButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')"><span class="sr-only">Checked</span><i class="fa fa-check greenCheck"></i><?=$list->title?></button>
                    </form>
                  <? else: ?>
                    <form method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>">
                      <input type="hidden" name="submit" value="1">
                      <input type="hidden" name="id" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown" onClick="$('.rightButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')"><?=$list->title?></button>
                    </form>
                  <? endif; ?>
                </li>
              <? endforeach; ?>
            <? endif; ?>
            <li><button class="btn-dropdown btn-standardDropdown" onclick="Lightbox.get('MyResearch','EditList',{'id':'NEW','recordId':'<?=$this->driver->getUniqueID()?>'})">New list...</button></li>
            <? if ($this->hasOnList): ?>
              <hr class="stretchHR">
              <li><span class="modalNote">Click a non-checked list to add this title.  Click a checked list to remove this title.</span></li>
            <? endif; ?>
          </ul>
        </div>
      </div>
      <div class="EIN-col-m-12 EIN-hide-t EIN-hide">
        <div class="dropdown" id="holdButtonDropdownMobile">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if( $this->ODread && $this->ODread["result"] ): ?>
              <li>
                <a href="<?=$this->ODread["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Read Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->ODlisten && $this->ODlisten["result"] ): ?>
              <li>
                <a href="<?=$this->ODlisten["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Listen Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->ODwatch && $this->ODwatch["result"] ): ?>
              <li>
                <a href="<?=$this->ODwatch["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Watch Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->downloadFormats && count($this->downloadFormats) > 0 ): ?>
              <?
                $streamingVideo = false;
                $nookPeriodical = false;
                foreach($this->downloadFormats as $thisFormat): 
                  $streamingVideo |= (strval($thisFormat["id"]) == "video-streaming");
                  $nookPeriodical |= (strval($thisFormat["id"]) == "periodicals-nook");
                endforeach;
              ?>
              <li>
                <button class="btn-dropdown btn-standardDropdown" onClick="Lightbox.get('Record','OverdriveDownload',<?=str_replace("}", (",'parentURL':'" . $this->CurrentPath() . "'}"), $this->idArgs)?>)"><?=($streamingVideo?"Watch Now":"Download")?></button>
              </li>
            <? endif; ?>
            <? if( $this->canReturn ): ?>
              <li>
                <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Return')?>" target="loginFrame">
                  <button class="btn-dropdown btn-standardDropdown" onClick="$('.leftButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')">Return</button>
                </a>
              </li>
            <? endif; ?>
          </ul>
        </div>
        <div class="dropdown" id="saveButtonDropdownMobile">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if($this->myLists): ?>
              <? foreach($this->myLists as $list): ?>
                <li>
                  <? if($list->contains($this->driver->getResourceSource()."|".$this->driver->getUniqueID())): ?>
                    <form method="post" action="<?=$this->url('userList', array('id' => $list->id))?>">
                      <input type="hidden" name="confirm" value="1">
                      <input type="hidden" name="delete" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="returnBibID" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown" onClick="$('.rightButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')"><span class="sr-only">Checked</span><i class="fa fa-check greenCheck"></i><?=$list->title?></button>
                    </form>
                  <? else: ?>
                    <form method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>">
                      <input type="hidden" name="submit" value="1">
                      <input type="hidden" name="id" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown" onClick="$('.rightButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')"><?=$list->title?></button>
                    </form>
                  <? endif; ?>
                </li>
              <? endforeach; ?>
            <? endif; ?>
            <li><button class="btn-dropdown btn-standardDropdown" onclick="Lightbox.get('MyResearch','EditList',{'id':'NEW','recordId':'<?=$this->driver->getUniqueID()?>'})">New list...</button></li>
            <? if ($this->hasOnList): ?>
              <hr class="stretchHR">
              <li><span class="modalNote">Click a non-checked list to add this title.  Click a checked list to remove this title.</span></li>
            <? endif; ?>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="EIN-col-m-12 padded">
    <div class="EIN-col-m-12">
      <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details1" class="leftTab collapsed">Availability Details</a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
        <div class="panel-heading" style="display:none">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details2" class="leftTab collapsed">Other Formats & Languages</a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
        <div class="panel-heading overdriveHeader">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details3" class="leftTab collapsed">Details</a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
        <div class="panel-heading"></div>
      </div>
      <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9">
      <div class="panel-group" id="detailsAccordion">
        <div class="panel panel-default detailAccordion">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details1" class="collapsed">Availability Details<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details1" class="panel-collapse collapse">
            <div class="panel-body" style="overflow-x:hidden">
              <? if( isset($this->holdings["CHECKIN_RECORDS"]) && $serialCheckinRecord ): ?>
                <? foreach( $this->holdings["CHECKIN_RECORDS"]["items"][0]["checkinRecords"] as $key => $thisRecord ): ?>
                  <? if( !$thisRecord["location"] ): continue; endif; ?>
                  <div class="EIN-col-m-12 checkinLoc">
                    <span class="checkinLocName"><?=($thisRecord["location"] ? $thisRecord["location"] : json_encode($thisRecord))?></span>
                    <? if( isset($thisRecord["identity"]) && $thisRecord["identity"] ): ?>
                      <span class="EIN-col-m-12 checkinLocDetail"><span style="font-weight:700">Identity:</span> <?=$thisRecord["identity"]?></span>
                    <? endif; ?>
                    <? if( isset($thisRecord["libHas"]) && $thisRecord["libHas"] ): ?>
                      <span class="EIN-col-m-12 checkinLocDetail"><span style="font-weight:700">Library Has:</span> <?=$thisRecord["libHas"]?></span>
                    <? endif; ?>
                    <? if( isset($thisRecord["latestReceived"]) && $thisRecord["latestReceived"] ): ?>
                      <span class="EIN-col-m-12 checkinLocDetail"><span style="font-weight:700">Latest Received:</span> <?=$thisRecord["latestReceived"]?></span>
                    <? endif; ?>
                    <? $issues = []; ?>
                    <? foreach($this->holdings as $thisHolding): ?>
                      <? foreach($thisHolding['items'] as $item): ?>
                        <? if( in_array($item['locationCode'], $thisRecord["code"]) ): ?>
                          <? $issues[] = $item; ?>
                        <? endif; ?>
                      <? endforeach; ?>
                    <? endforeach; ?>
                    <? if( count($issues) > 0 ): ?>
                      <? $issueHash = md5($key); ?>
                      <div class="EIN-col-m-12" id="accordionMore<?=$issueHash?>"><a class="checkinLocDetail" onClick="ToggleAccordion('<?=$issueHash?>',false);">Show Issues (<?=count($issues)?>)</a></div>
                      <div class="EIN-col-m-12" id="accordionLess<?=$issueHash?>" style="display:none">
                        <a class="checkinLocDetail" onClick="ToggleAccordion('<?=$issueHash?>',true);">Hide Issues</a>
                        <table class="EIN-col-m-12">
                          <tr class="availabilityHeaderRow EIN-hide-m">
                            <td class="EIN-col-m-4">Volume</td>
                            <td class="EIN-col-m-4">Status</td>
                          </tr>
                          <? foreach( $issues as $thisIssue ): ?>
                            <? /* tablet/desktop UI (two columns) */ ?>
                            <tr class="availabilityRow EIN-hide-m">
                              <td class="EIN-col-m-8"><?=(isset($thisIssue['number']) ? $thisIssue['number'] : "UNKNOWN")?></td>
                              <td class="EIN-col-m-4"><?=(isset($thisIssue['displayStatus']) ? $thisIssue['displayStatus'] : "UNKNOWN")?></td>
                            </tr>
                            <? /* mobile UI (two rows) */ ?>
                            <tr class=" EIN-hide-t EIN-hide">
                              <td class="availabilityRowFieldName">Volume&nbsp;</td>
                              <td><?=(isset($thisIssue['number']) ? $thisIssue['number'] : "UNKNOWN")?></td>
                            </tr>
                            <tr class=" EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                            <tr class=" EIN-hide-t EIN-hide">
                              <td class="availabilityRowFieldName">Status&nbsp;</td>
                              <td><?=(isset($thisIssue['displayStatus']) ? $thisIssue['displayStatus'] : "UNKNOWN")?></td>
                            </tr>
                            <tr class="availabilityRowEnd EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                            <tr class=" EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                          <? endforeach; ?>
                        </table>
                      </div>
                    <? endif; ?>
                  </div>
                <? endforeach; ?>
              <? else: ?>
                <? if( $noncirculatingCopies > 0 ): ?>
                  <h6 style="font-weight:700">Noncirculating (<?=$noncirculatingCopies?>)</h6>
                  <table class="EIN-col-m-12">
                    <? /* tablet/desktop UI (three columns) */ ?>
                    <tr class="availabilityHeaderRow EIN-hide-m">
                      <td class="EIN-col-m-4">Location</td>
                      <td class="EIN-col-m-4">Collection</td>
                      <td class="EIN-col-m-4">Call #</td>
                    </tr>
                    <? foreach($this->holdings as $thisHolding): ?>
                      <? foreach($thisHolding['items'] as $item): ?>
                        <? if($item['availability'] && ($item['status'] == "o")): ?>
                          <? /* tablet/desktop UI (three columns) */ ?>
                          <tr class="availabilityRow EIN-hide-m">
                            <td class="EIN-col-m-4"><?=(isset($item['branchName']) ? $item['branchName'] : "UNKNOWN")?></td>
                            <td class="EIN-col-m-4"><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "UNKNOWN")?></td>
                            <td class="EIN-col-m-4 callNumberBreaker"><?=(isset($item['callnumber']) ? ($item['callnumber'] . (($item["number"] != null) ? (" " . $item["number"]) : "")) : "UNKNOWN")?></td>
                          </tr>
                          <? /* mobile UI (three rows) */ ?>
                          <tr class="EIN-hide-t EIN-hide">
                            <td class="availabilityRowFieldName">Location&nbsp;</td>
                            <td><?=(isset($item['branchName']) ? $item['branchName'] : "UNKNOWN")?></td>
                          </tr>
                          <tr class="EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                          <tr class="EIN-hide-t EIN-hide">
                            <td class="availabilityRowFieldName">Collection&nbsp;</td>
                            <td><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "UNKNOWN")?></td>
                          </tr>
                          <tr class="EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                          <tr class="EIN-hide-t EIN-hide">
                            <td class="availabilityRowFieldName">Call Number&nbsp;</td>
                            <td><?=(isset($item['callnumber']) ? ($item['callnumber'] . (($item["number"] != null) ? (" " . $item["number"]) : "")) : "UNKNOWN")?></td>
                          </tr>
                          <tr class="availabilityRowEnd EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                          <tr class="EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                        <? endif; ?>
                      <? endforeach; ?>
                    <? endforeach; ?>
                  </table>
                  <? if( $noncirculatingCopies != $totalCopies ): ?>
                    <span class="accordionGap">&nbsp;</span>
                  <? endif; ?>
                <? endif; ?>
                <? if( (($availableCopies - $noncirculatingCopies) > 0) || $isOneClick ): ?>
                  <h6 class="accordionSubheading">Available<?=($isOverDrive?" on OverDrive":($isOneClick?" on OneClick":""))?> (<?=($alwaysAvailable || $isOneClick) ? "Always Available" : ($availableCopies - $noncirculatingCopies)?>)</h6>
                  <? if( !$isOverDrive && !$isOneClick ): ?>
                    <table class="EIN-col-m-12">
                      <? /* tablet/desktop UI (three columns) */ ?>
                      <tr class="availabilityHeaderRow EIN-hide-m">
                        <td class="EIN-col-m-4">Location</td>
                        <td class="EIN-col-m-4">Collection</td>
                        <td class="EIN-col-m-4">Call #</td>
                      </tr>
                      <? foreach($this->holdings as $thisHolding): ?>
                        <? foreach($thisHolding['items'] as $item): ?>
                          <? if($item['availability'] && ($item['status'] != "o")): ?>
                            <? /* tablet/desktop UI (three columns) */ ?>
                            <tr class="availabilityRow EIN-hide-m">
                              <td class="EIN-col-m-4"><?=(isset($item['branchName']) ? $item['branchName'] : "UNKNOWN")?></td>
                              <td class="EIN-col-m-4"><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "UNKNOWN")?></td>
                              <td class="EIN-col-m-4 callNumberBreaker"><?=(isset($item['callnumber']) ? ($item['callnumber'] . (($item["number"] != null) ? (" " . $item["number"]) : "")) : "UNKNOWN")?></td>
                            </tr>
                            <? /* mobile UI (three rows) */ ?>
                            <tr class="EIN-hide-t EIN-hide">
                              <td class="availabilityRowFieldName">Location&nbsp;</td>
                              <td><?=(isset($item['branchName']) ? $item['branchName'] : "UNKNOWN")?></td>
                            </tr>
                            <tr class="EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                            <tr class="EIN-hide-t EIN-hide">
                              <td class="availabilityRowFieldName">Collection&nbsp;</td>
                              <td><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "UNKNOWN")?></td>
                            </tr>
                            <tr class="EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                            <tr class="EIN-hide-t EIN-hide">
                              <td class="availabilityRowFieldName">Call Number&nbsp;</td>
                              <td><?=(isset($item['callnumber']) ? ($item['callnumber'] . (($item["number"] != null) ? (" " . $item["number"]) : "")) : "UNKNOWN")?></td>
                            </tr>
                            <tr class="availabilityRowEnd EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                            <tr class="EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                          <? endif; ?>
                        <? endforeach; ?>
                      <? endforeach; ?>
                    </table>
                  <? endif; ?>
                  <? if( !$alwaysAvailable && $totalCopies > 0 && $totalCopies != $availableCopies ): ?>
                    <span class="accordionGap">&nbsp;</span>
                  <? endif; ?>
                <? endif; ?>
                <? if( !$alwaysAvailable && $totalCopies > 0 && $totalCopies != $availableCopies ): ?>
                  <h6 class="accordionSubheading">Unavailable<?=($isOverDrive?" on OverDrive":"")?> (<?=($totalCopies - $availableCopies)?>)</h6>
                  <? if( !$isOverDrive ): ?>
                    <table class="EIN-col-m-12">
                      <? /* tablet/desktop UI (three columns) */ ?>
                      <tr class="availabilityHeaderRow EIN-hide-m">
                        <td class="EIN-col-m-4">Location</td>
                        <td class="EIN-col-m-4">Collection</td>
                        <td class="EIN-col-m-4">Status</td>
                      </tr>
                      <? foreach($this->holdings as $thisHolding): ?>
                        <? foreach($thisHolding['items'] as $item): ?>
                          <? if(!$item['availability'] && ($item['status'] != "o") && ($item['location'] != "CHECKIN_RECORDS")): ?>
                            <? for( $j=0; $j<(($item['status'] == "order") ? $item['copiesOwned'] : 1); $j++ ): ?>
                              <? /* tablet/desktop UI (three columns) */ ?>
                              <tr class="availabilityRow EIN-hide-m">
                                <td class="EIN-col-m-4"><?=(isset($item['branchName']) ? $item['branchName'] : "UNKNOWN")?></td>
                                <td class="EIN-col-m-4"><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "UNKNOWN")?></td>
                                <td class="EIN-col-m-4"><?=((isset($item['displayStatus']) ? $item['displayStatus'] : "UNKNOWN") . (($item["number"] != null) ? (" (" . $item["number"] . ")") : ""))?></td>
                              </tr>
                              <? /* mobile UI (three rows) */ ?>
                              <tr class=" EIN-hide-t EIN-hide">
                                <td class="availabilityRowFieldName">Location&nbsp;</td>
                                <td><?=(isset($item['branchName']) ? $item['branchName'] : "UNKNOWN")?></td>
                              </tr>
                              <tr class=" EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                              <tr class=" EIN-hide-t EIN-hide">
                                <td class="availabilityRowFieldName">Collection&nbsp;</td>
                                <td><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "UNKNOWN")?></td>
                              </tr>
                              <tr class=" EIN-hide-t EIN-hide"><td colspan="2" style="font-size:3px">&nbsp;</td></tr>
                              <tr class=" EIN-hide-t EIN-hide">
                                <td class="availabilityRowFieldName">Status&nbsp;</td>
                                <td><?=((isset($item['displayStatus']) ? $item['displayStatus'] : "UNKNOWN") . (($item["number"] != null) ? (" (" . $item["number"] . ")") : ""))?></td>
                              </tr>
                              <tr class="availabilityRowEnd EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                              <tr class=" EIN-hide-t EIN-hide"><td colspan="2" style="font-size:8px">&nbsp;</td></tr>
                            <? endfor; ?>
                          <? endif; ?>
                        <? endforeach; ?>
                      <? endforeach; ?>
                    </table>
                  <? endif; ?>
                <? endif; ?>
              <? endif; ?>
            </div>
          </div>
        </div>
        <div class="panel panel-default detailAccordion" style="display:none">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details2" class="collapsed">Other Formats & Languages<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details2" class="panel-collapse collapse">
            <div class="panel-body">
              <span>Something</span>
            </div>
          </div>
        </div>
        <div class="panel panel-default detailAccordion">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details3" class="collapsed">Details<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details3" class="panel-collapse collapse">
            <div class="panel-body">
              <? if( isset($this->tabs['Summaries']) || count($this->driver->getSummary()) > 0 ): ?>
                <? $summarySources = (isset($this->tabs['Summaries']) ? $this->tabs['Summaries']->getContent($this->driver->getCleanISBN()) : []); ?>
                <? if( count($summarySources) > 0 ): ?>
                  <h6 class="accordionSubheading accordionGap">Summary</h6>
                  <? foreach( $summarySources as $summaries ): ?>
                    <? foreach( $summaries as $summary ): ?>
                      <div class="accordionParagraph"><?=$summary['Content']?></div>
                    <? endforeach; ?>
                  <? endforeach; ?>
                <? elseif( count($summaries = $this->driver->getSummary()) > 0 ): ?>
                  <h6 class="accordionSubheading accordionGap">Summary</h6>
                  <span class="accordionParagraph">
                  <? foreach( $summaries as $summary ): ?>
                    <?=$summary ?><br>
                  <? endforeach; ?>
                  </span>
                <? endif; ?>
              <? endif; ?>
              <? if( count($toc = $this->driver->getTOC()) > 0 ): ?>
                <h6 class="accordionSubheading accordionGap">Contents</h6>
                <span class="accordionParagraph">
                  <? foreach( $toc as $line ): ?>
                    <?=(($line == "") ? " --<br>" : $line) ?>
                  <? endforeach; ?>
                </span><br>
              <? endif; ?>
              <? if( isset($this->tabs['Reviews']) ): ?>
                <? $reviewSources = $this->tabs['Reviews']->getContent($this->driver->getCleanISBN()); ?>
                <? if( count($reviewSources) > 0 ): ?>
                  <h6 class="accordionSubheading accordionGap">Published Reviews</h6>
                  <? foreach( $reviewSources as $reviews ): ?>
                    <? foreach( $reviews as $review ): ?>
                      <span class="reviewSource"><?=$review['Source']?>: </span>
                      <span class="accordionParagraph">"<?=$review['Content']?>"</span><br>
                      <span class="EIN-col-m-12 reviewCopyright"><?=$review['Copyright']?></span><br>
                    <? endforeach; ?>
                  <? endforeach; ?>
                <? endif; ?>
              <? endif; ?>
              <h6 class="accordionSubheading accordionGap">Additional Information</h6>
              <table class="EIN-col-m-12 accordionTable">
                <? if( isset($this->tabs['Series']) ): ?>
                  <? $seriesInfo = $this->tabs['Series']->getContent($this->driver->getCleanISBN()); ?>
                  <? if( count($seriesInfo) > 0 ): ?>
                    <tr>
                      <td class="colophonHeading"><?=$this->transEsc('Series')?></td>
                      <td><span class="accordionParagraph">
                        <? foreach($seriesInfo as $sourceIndex => $thisSource): ?>
                          <? if( $sourceIndex == "Syndetics" ): ?>
                            <? foreach($thisSource as $seriesIndex => $thisSeries): ?>
                              <? $marcSeriesTitle = $this->driver->getSeries(); ?>
                              <? $marcSeriesNumber = ((count($marcSeriesTitle) && isset($marcSeriesTitle[0]["number"])) ? $marcSeriesTitle[0]["number"] : ""); ?>
                              <? $marcSeriesTitle = ((count($marcSeriesTitle) && isset($marcSeriesTitle[0]["name"])) ? $marcSeriesTitle[0]["name"] : $thisSeries["title"]); ?>
                              <span style="font-weight:700"><a href="<?=$this->record($this->driver)->getLink('series', $marcSeriesTitle)?>"><?=($marcSeriesTitle . " " . $marcSeriesNumber)?></a><br>
                              <? if( isset($thisSeries["notes"]) ): ?>
                                <span><?=$thisSeries["notes"] ?></span><br>
                              <? endif; ?>
                              <? $i=1; while( isset($thisSeries[$i]) ): ?>
                                <span>#<?=$i?> - <a href="<?=$this->record($this->driver)->getLink('title', $thisSeries[$i]["title"])?>"><?=$thisSeries[$i]["title"]?></a></span><br>
                                <? $i++; ?>
                              <? endwhile; ?>
                            <? endforeach; ?>
                          <? endif; ?>
                        <? endforeach; ?>
                      </span></td>
                    </tr>
                  <? else: ?>
                    <? $marcSeriesTitle = $this->driver->getSeries(); ?>
                    <? $marcSeriesNumber = ((count($marcSeriesTitle) && isset($marcSeriesTitle[0]["number"])) ? $marcSeriesTitle[0]["number"] : ""); ?>
                    <? $marcSeriesTitle = ((count($marcSeriesTitle) && isset($marcSeriesTitle[0]["name"])) ? $marcSeriesTitle[0]["name"] : ""); ?>
                    <? if( $marcSeriesTitle ): ?>
                      <tr>
                        <td class="colophonHeading"><?=$this->transEsc('Series')?></td>
                        <td><span class="accordionParagraph">
                          <span style="font-weight:700"><a href="<?=$this->record($this->driver)->getLink('series', $marcSeriesTitle)?>"><?=($marcSeriesTitle . " " . $marcSeriesNumber)?></a></span>
                        </span></td>
                      </tr>
                    <? endif; ?>
                  <? endif; ?>
                <? endif; ?>
                <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Subjects')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach($subjects as $thisSubject): ?>
                        <? $subjectSearch = ""; ?>
                        <? foreach( $thisSubject as $headingIndex => $thisHeading ): ?>
                          <? $subjectSearch .= ($headingIndex ? "  " : "") . $thisHeading; ?>
                          <span><?=($headingIndex ? " -- " : "")?><a href="<?=$this->record($this->driver)->getLink('subject', $subjectSearch)?>"><?= $thisHeading ?></a></span>
                        <? endforeach; ?><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Publisher')?></td>
                    <td><? foreach($publications as $thisPublication): ?>
                      <span><?= $this->escapeHtml($thisPublication->getPlace()) . $this->escapeHtml($thisPublication->getName()) . $this->escapeHtml($thisPublication->getDate()) ?></span><br>
                    <? endforeach; ?></td>
                  </tr>
                <? endif; ?>
                <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Edition')?></td>
                    <td><?=$this->escapeHtml($edition)?></td>
                  </tr>
                <? endif; ?>
                <? $otherTitles = array_merge($this->driver->getNewerTitles(), $this->driver->getPreviousTitles(), $this->driver->getFormattedMarcDetails(730, ['|a']), $this->driver->getFormattedMarcDetails(740, ['|a']), $this->driver->getFormattedMarcDetails(700, ['|t']), $this->driver->getFormattedMarcDetails(710, ['|t']), $this->driver->getFormattedMarcDetails(711, ['|t']), $this->driver->getFormattedMarcDetails(240, ['|a']), $this->driver->getFormattedMarcDetails(246, ['|a'])); ?>
                <? foreach( $otherTitles as $otIndex => $thisTitle ): ?>
                  <? if( isset($thisTitle["0"]) && ($thisTitle["0"] == "") ): unset($otherTitles[$otIndex]); endif; ?>
                <? endforeach; ?>
                <? if (!empty($otherTitles)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Other Titles')?></td>
                    <td><span class="accordionParagraph"><? foreach ($otherTitles as $altTitle): ?>
                      <? $field = isset($altTitle[0]) ? $altTitle[0] : $altTitle; ?>
                      <? if( $field != "" ): ?>
                        <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$field?></a><br>
                      <? endif; ?>
                    <? endforeach; ?></span></td>
                  </tr>
                <? endif; ?>
                <? $contributors = array_merge($this->driver->getFormattedMarcDetails(700, ['|a']), $this->driver->getFormattedMarcDetails(710, ['|a']), $this->driver->getFormattedMarcDetails(711, ['|a'])); ?>
                <? if (count($contributors) > 0): ?>
                  <? $roles = array_merge($this->driver->getFormattedMarcDetails(700, ['|bdqce4']), $this->driver->getFormattedMarcDetails(710, ['|bdce']), $this->driver->getFormattedMarcDetails(711, ['|dce'])); ?>
                  <? $titles = array_merge($this->driver->getFormattedMarcDetails(700, ['|t']), $this->driver->getFormattedMarcDetails(710, ['|t']), $this->driver->getFormattedMarcDetails(711, ['|t'])); ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Contributors')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($contributors as $key => $field): ?>
                        <span property="contributor">
                          <a href="<?=$this->record($this->driver)->getLink('contributor', $field[0])?>"><?=$this->escapeHtml($field[0])?></a>
                          <? if( $roles[$key][0] != "" ): ?>
                            <?= $roles[$key][0] ?>
                          <? endif; ?>
                          <? if( $titles[$key][0] != "" ): ?>
                            <a href="<?=$this->record($this->driver)->getLink('title', $titles[$key][0])?>"><?= $titles[$key][0] ?></a>
                          <? endif; ?>
                        </span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $performerNotes = $this->driver->getFormattedMarcDetails(511, ['|a']); ?>
                <? if (count($performerNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Participants/Performers')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($performerNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field[0])?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $productionNotes = $this->driver->getProductionCredits(); ?>
                <? if (count($productionNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Other Contributors')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($productionNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $targetNotes = $this->driver->getTargetAudienceNotes(); ?>
                <? if (count($targetNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Audience')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($targetNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $langs = $this->driver->getLanguages(); ?>
                <? $languageNotes = $this->driver->getFormattedMarcDetails(546, ['|a']); ?>
                <? if ( (count($langs) + count($languageNotes)) > 0 ): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Language')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($langs as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                      <? foreach ($languageNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field[0])?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $generalNotes = $this->driver->getGeneralNotes(); ?>
                <? if (count($generalNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Notes')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($generalNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $systemNotes = $this->driver->getSystemDetails(); ?>
                <? if (count($systemNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('System Details')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($systemNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $awardNotes = $this->driver->getAwards(); ?>
                <? if (count($awardNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Awards')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($awardNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $marcDesc = $this->driver->getFormattedMarcDetails(300,['|abce']); ?>
                <? if (count($marcDesc) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Description')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($marcDesc as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field[0])?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $bibNotes = $this->driver->getBibliographyNotes(); ?>
                <? if (count($bibNotes) > 0): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Bibliography Notes')?></td>
                    <td><span class="accordionParagraph">
                      <? foreach ($bibNotes as $field): ?>
                        <span property="contributor"><?=$this->escapeHtml($field)?></span><br>
                      <? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('ISBN')?></td>
                    <td><? foreach ($isbns as $isbn): ?><?= $this->escapeHtml($isbn)?><br/><? endforeach; ?></td>
                  </tr>
                <? endif; ?>
                <? if (!empty($urls)): ?>
                  <tr>
                    <td class="colophonHeading">Links</td>
                    <td><span class="accordionParagraph">
                      <? foreach ($urls as $url): ?><div class="itemURL"><a href="<?=$url["url"]?>" target="_blank"><?=($isOneClick ? 'Download from OneClick' : $url["desc"])?></a></div><? endforeach; ?>
                    </span></td>
                  </tr>
                <? endif; ?>
                <? if( isset($this->classicLink)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Other')?></td>
                    <td><a href="<?=$this->classicLink?>" target="_blank">Classic View</a></td>
                  </tr>
                <? endif; ?>
              </table>
            </div>
          </div>
        </div>
      </div>
      </div>
      <script type="text/javascript">
        $('.panel-heading a').on('click',function(e){
          // prevent them from dismissing the last open section if we're in tablet or desktop layout
          if($(document).width() >= 600) {
            if($($(this).attr("href")).hasClass('in')){
              e.stopPropagation();
            }
            // You can also add preventDefault to remove the anchor behavior that makes the page jump
            e.preventDefault();
          }
        });
        $('body').css({"overflow-y":"hidden"});
        if($(document).width() >= 600) {
          $('.panel-heading<?=($isOverDrive?".overdriveHeader":"")?> a').first().click();
          $('.panel-heading<?=($isOverDrive?".overdriveHeader":"")?> a[href="#details3"]').click();
        }
        $('body').css({"overflow-y":"auto"});
        $('#detailsAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});

        // do some expansion checking for long details
        $(".accordionParagraph").each( function() {
          var contents = $(this).html().replace(/ {2,}/g,' ');
          if(contents.length > 300) {
            var hash = hashString(contents);
            // remove links, since those blow out our string length
            var cleanContents = contents.substring(0);
            var removedLinks = {};
            var openStartPos, openEndPos, closeStartPos, closeEndPos;
            while((openStartPos = cleanContents.lastIndexOf("<a")) > 0) {
              openEndPos = cleanContents.indexOf(">", openStartPos) + 1;
              closeStartPos = cleanContents.indexOf("</a>", openStartPos);
              closeEndPos = cleanContents.indexOf(">", closeStartPos) + 1;
              removedLinks[openStartPos] = cleanContents.substring(openStartPos, openEndPos);
              removedLinks[closeStartPos] = cleanContents.substring(closeStartPos, closeEndPos);
              cleanContents = cleanContents.substring(0, openStartPos) + cleanContents.substring(openEndPos, closeStartPos) + cleanContents.substring(closeEndPos);
            }
            if(cleanContents.length > 300) {
              var breakPoint = cleanContents.indexOf("<br>");
              while(breakPoint > -1 && cleanContents.indexOf("<br>", breakPoint + 1) < 300) {
                breakPoint = cleanContents.indexOf("<br>", breakPoint + 1);
              }
              if( breakPoint == -1 ) {
                breakPoint = cleanContents.indexOf("<div class=\"itemURL\">");
                while(breakPoint > -1 && cleanContents.indexOf("<div class=\"itemURL\">", breakPoint + 1) < 300) {
                  breakPoint = cleanContents.indexOf("<div class=\"itemURL\">", breakPoint + 1);
                }
              }
              if( breakPoint == -1 || breakPoint > 300 ) {
                breakPoint = 300;
              }
              // put the links back in for the less version
              var closeLink = false;
              var finished = false;
              for(var key in removedLinks) {
                if( !finished && ((key < breakPoint) || closeLink) ) {
                  if( key >= breakPoint ) {
                    breakPoint = parseInt(key) + 4;
                    finished = true;
                  } else {
                    breakPoint += removedLinks[key].length;
                  }
                  closeLink = !closeLink;
                }
              }
              $(this).html("");
              $(this).append("<span id=\"accordionLess" + hash + "\">" + contents.substring(0,breakPoint) + " ... <a class=\"moreLink\" onClick=\"ToggleAccordion(" + hash + ",1)\">More</a></span>");
              $(this).append("<span id=\"accordionMore" + hash + "\" style=\"display:none\">" + contents + " <a class=\"moreLink\" onClick=\"ToggleAccordion(" + hash + ",0)\">Less</a></span>");
            }
          }
        } );

        /***** For now, we're just showing the highlights on the search results page *****\
        // do the search highlighting
        var searchTerms = <?=json_encode($this->searchMemory)?>;
        for(var index in searchTerms) {
          var position = $(".itemTitle").html().length;
          position = $(".itemTitle").html().lastIndexOf(searchTerms[index])
        //$(".itemTitle").html($(".itemTitle").html().replace(/));
        }
        \***** For now, we're just showing the highlights on the search results page *****/

        function ToggleAccordion(hashCode,showMore) {
          $('#accordionMore' + hashCode).css({"display":(showMore ? "inline" : "none")});
          $('#accordionLess' + hashCode).css({"display":(showMore ? "none" : "inline")});
          moveButtons();
        }

        function hashString(str){
          var hash = 0;
          if (str.length == 0) return hash;
          for (i = 0; i < str.length; i++) {
            char = str.charCodeAt(i);
            hash = ((hash<<5)-hash)+char;
            hash = hash & hash; // Convert to 32bit integer
          }
          return hash;
        }
      </script>
    </div>
  </div>
</div>
