<?
  // Set up convenience variables:
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $record = $this->record($this->driver);
  $isOverDrive = false;
  foreach($this->holdings as $entry):
    foreach($entry["items"] as $item):
      if( isset($item["isOverDrive"]) && $item["isOverDrive"] ):
        $isOverDrive = true;
      endif;
    endforeach;
  endforeach;
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="EIN-col-m-12 EIN-col-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $record->getThumbnail('medium'); $largeThumb = $record->getThumbnail('large'); ?>
      <? if ($largeThumb): ?>
        <a href="<?=$this->escapeHtmlAttr($largeThumb)?>">
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($largeThumb);?>"/>
        </a>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $record->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$record->getPreviews()?>
  </div>

  <div class="EIN-col-m-12 EIN-col-9 padded">
    <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
      <h1 property="name" class="itemTitle"><?=$this->escapeHtml($isOverDrive ? trim($this->driver->getTitle(),"\0\t\n\x0B\r /") : (trim($this->driver->getShortTitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getSubtitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getTitleSection(),"\0\t\n\x0B\r /")))?></h1>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <h4 property="author" class="itemAuthor">by <a href="<?=$record->getLink('author', $authors['main'])?>" class="authorLink"><?=$this->escapeHtml($authors['main'])?></a></h4>
      <? endif; ?>

      <table>
        <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
          <? $firstTime = true; foreach( $formats as $thisFormat ): ?>
            <tr>
              <td class="EIN-hide-m itemDetailCategory"><?=($firstTime?"Format:":"&nbsp;")?></td>
              <td style="padding-bottom:5px">
                <span class="formatTag"><?=$thisFormat?></span>

                <? if( $firstTime ): ?>
                  <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                    <? foreach ($publications as $field): ?>
                      <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                        <span property="publicationDate" class="publishDate"><?=$this->escapeHtml($pubDate)?></span>
                      <? endif; ?>
                    <? endforeach; ?>
                  <? endif; ?>
                  <? $firstTime = false; ?>
                <? endif; ?>
              </td>
            </tr>
          <? endforeach; ?>
        <? endif; ?>

        <tr>
          <? $totalCopies = 0; $availableCopies = 0; $firstTime = true;?>
          <? foreach($this->holdings as $entry): ?>
            <? $firstTime = false; ?>
            <? foreach($entry["items"] as $item): ?>
              <? if( isset($item["isOverDrive"]) && $item["isOverDrive"] ): ?>
                <? $totalCopies += ($item["copiesOwned"]); $availableCopies += ($item["copiesAvailable"]); ?>
              <? else: ?>
                <? $totalCopies++; $availableCopies += ($item["availability"]); ?>
              <? endif; ?>
            <? endforeach; ?>
          <? endforeach; ?>
          <? $green = (($totalCopies > 0) && ($availableCopies > 0)); ?>
          <td class="EIN-hide-m itemDetailCategory">Availability:</td>
          <td style="padding-bottom:5px">
            <span class="<?=($green ? "availableTag" : "unavailableTag")?>"><?=($green ? '<i class="fa fa-check"></i>Available' : "Unavailable")?></span>
            <span class="<?=($green ? "availableCopyText" : "unavailableCopyText")?>"><?=((($totalCopies > 0) ? ($availableCopies . " of ") : "") . $totalCopies . " cop" . (($totalCopies == 1) ? "y" : "ies"))?></span>
          </td>
        </tr>
      </table>

      <?
        if($user && $this->isTitleCheckedOut && $isOverDrive):
          $holdClick = " data-toggle=\"dropdown\" data-target=\"#holdButtonDropdown\"";
          $saveClick = " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown\"";
        elseif($user):
          $holdClick = " onClick=\"Lightbox.get('Record'," . ((!$this->canHold && $this->canCheckOut) ? ("'Checkout'," . $this->idArgs) : ("'Hold'," . $this->holdArgs)) . ")\"";
          $saveClick = " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown\"";
        else:
          $holdClick = " onClick=\"Lightbox.get('MyResearch','Login')\"";
          $saveClick = " onClick=\"Lightbox.get('MyResearch','Login')\"";
        endif;

        $holdLabel = ($this->canHold ? "Hold" : ($this->isTitleHeld ? "Holding" : ($this->canCheckOut ? "Check Out" : ($this->isTitleCheckedOut ? "Checked Out" : "Unable to Hold"))));
        if( $this->isTitleCheckedOut && $isOverDrive ):
          $holdLabel .= "<i class=\"fa fa-caret-down\"></i>";
        endif;
      ?>
    </div>
    <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4" style="padding:5px 0px 10px">
      <div class="EIN-col-m-6 EIN-col-t-12 EIN-col-12">
        <button class="btn-default leftButton"<?=$holdClick?><?=(($this->canHold || $this->canCheckOut || ($isOverDrive && $this->isTitleCheckedOut))?"":" disabled")?>><?=$holdLabel?></button>
        <div class="EIN-col-m-12 dropdown" id="holdButtonDropdown">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if( $this->ODread && $this->ODread["result"] ): ?>
              <li>
                <a href="<?=$this->ODread["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Read Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->ODlisten && $this->ODlisten["result"] ): ?>
              <li>
                <a href="<?=$this->ODlisten["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Listen Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->ODwatch && $this->ODwatch["result"] ): ?>
              <li>
                <a href="<?=$this->ODwatch["downloadUrl"]?>" target="_blank"><button class="btn-dropdown btn-standardDropdown">Watch Now</button></a>
              </li>
            <? endif; ?>
            <? if( $this->downloadFormats && count($this->downloadFormats) > 0 ): ?>
              <?
                $streamingVideo = false;
                foreach($this->downloadFormats as $thisFormat): 
                  $streamingVideo |= ($thisFormat["id"] == "video-streaming");
                endforeach;
              ?>
              <li>
                <button class="btn-dropdown btn-standardDropdown" onClick="Lightbox.get('Record','OverdriveDownload',<?=$this->idArgs?>)"><?=($streamingVideo?"Watch Now":"Download")?></button>
              </li>
            <? endif; ?>
            <? if( $this->canReturn ): ?>
              <li>
                <button class="btn-dropdown btn-standardDropdown" onClick="Lightbox.get('Record','Return',<?=$this->idArgs?>)">Return</button>
              </li>
            <? endif; ?>
          </ul>
        </div>
      </div>
      <div class="EIN-col-m-6 EIN-col-t-12 EIN-col-12">
        <button class="btn-default rightButton"<?=$saveClick?>><?=($this->hasOnList)?"Manage Lists":"Add to List"?><?=($user?"<i class=\"fa fa-caret-down\"></i>":"")?></button>
        <div class="EIN-col-m-12 dropdown" id="saveButtonDropdown">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if($this->myLists): ?>
              <? foreach($this->myLists as $list): ?>
                <li>
                  <? if($list->contains($this->driver->getResourceSource()."|".$this->driver->getUniqueID())): ?>
                    <form method="post" action="<?=$this->url('userList', array('id' => $list->id))?>">
                      <input type="hidden" name="confirm" value="1">
                      <input type="hidden" name="delete" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="returnBibID" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown"><i class="fa fa-check greenCheck"></i><?=$list->title?></button>
                    </form>
                  <? else: ?>
                    <form method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>">
                      <input type="hidden" name="submit" value="1">
                      <input type="hidden" name="id" value="<?=$this->driver->getUniqueID()?>">
                      <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                      <input type="hidden" name="list" value="<?=$list->id?>">
                      <button class="btn-dropdown btn-standardDropdown"><?=$list->title?></button>
                    </form>
                  <? endif; ?>
                </li>
              <? endforeach; ?>
            <? endif; ?>
            <li><button class="btn-dropdown btn-standardDropdown" onclick="Lightbox.get('MyResearch','EditList',{'id':'NEW','recordId':'<?=$this->driver->getUniqueID()?>'})">New list...</button></li>
            <? if ($this->hasOnList): ?>
              <hr class="stretchHR">
              <li><span class="modalNote">Click a non-checked list to add this title.  Click a checked list to remove this title.</span></li>
            <? endif; ?>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="EIN-col-m-12 padded">
    <div class="EIN-col-m-12">
      <div class="EIN-hide-m EIN-col-t-3 EIN-col-3 accordionButtonsLeft">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details1" class="collapsed">Availability Details</a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
        <div class="panel-heading" style="display:none">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details2" class="collapsed">Other Formats & Languages</a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
        <div class="panel-heading overdriveHeader">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details3" class="collapsed">Details</a>
            <div class="openAccordionTab"></div>
          </h4>
        </div>
        <div class="panel-heading"></div>
      </div>
      <div class="EIN-col-m-12 EIN-col-t-9 EIN-col-9">
      <div class="panel-group" id="detailsAccordion">
        <div class="panel panel-default detailAccordion">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details1" class="collapsed">Availability Details<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details1" class="panel-collapse collapse">
            <div class="panel-body">
              <? if( $availableCopies > 0): ?>
                <h6 class="accordionSubheading">Available<?=($isOverDrive?" on OverDrive":"")?> (<?=$availableCopies?>)</h6>
                <? if( !$isOverDrive ): ?>
                  <table class="EIN-col-m-12">
                    <tr class="availabilityHeaderRow">
                      <td class="EIN-col-m-4">Location</td>
                      <td class="EIN-col-m-4">Collection</td>
                      <td class="EIN-col-m-4">Call #</td>
                    </tr>
                    <? foreach($this->holdings as $thisHolding): ?>
                      <? foreach($thisHolding['items'] as $item): ?>
                        <? if($item['availability']): ?>
                          <tr class="availabilityRow">
                            <td class="EIN-col-m-4"><?=(isset($item['branchName']) ? $item['branchName'] : json_encode($item))?></td>
                            <td class="EIN-col-m-4"><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "")?></td>
                            <td class="EIN-col-m-4"><?=(isset($item['callnumber']) ? $item['callnumber'] : "")?></td>
                          </tr>
                        <? endif; ?>
                      <? endforeach; ?>
                    <? endforeach; ?>
                  </table>
                <? endif; ?>
              <? endif; ?>
              <? if( $totalCopies > 0 && $totalCopies != $availableCopies && $availableCopies > 0): ?>
                <span class="accordionGap">&nbsp;</span>
              <? endif; ?>
              <? if( $totalCopies > 0 && $totalCopies != $availableCopies ): ?>
                <h6 class="accordionSubheading">Unavailable<?=($isOverDrive?" on OverDrive":"")?> (<?=($totalCopies - $availableCopies)?>)</h6>
                <? if( !$isOverDrive ): ?>
                  <table class="EIN-col-m-12">
                    <tr class="availabilityHeaderRow">
                      <td class="EIN-col-m-4">Location</td>
                      <td class="EIN-col-m-4">Collection</td>
                      <td class="EIN-col-m-4">Status</td>
                    </tr>
                    <? foreach($this->holdings as $thisHolding): ?>
                      <? foreach($thisHolding['items'] as $item): ?>
                        <? if(!$item['availability']): ?>
                          <tr class="availabilityRow">
                            <td class="EIN-col-m-4"><?=(isset($item['branchName']) ? $item['branchName'] : json_encode($item))?></td>
                            <td class="EIN-col-m-4"><?=(isset($item['shelvingLocation']) ? $item['shelvingLocation'] : "")?></td>
                            <td class="EIN-col-m-4"><?=(isset($item['displayStatus']) ? $item['displayStatus'] : "")?></td>
                          </tr>
                        <? endif; ?>
                      <? endforeach; ?>
                    <? endforeach; ?>
                  </table>
                <? endif; ?>
              <? endif; ?>
            </div>
          </div>
        </div>
        <div class="panel panel-default detailAccordion" style="display:none">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details2" class="collapsed">Other Formats & Languages<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details2" class="panel-collapse collapse">
            <div class="panel-body">
              <span>Something</span>
            </div>
          </div>
        </div>
        <div class="panel panel-default detailAccordion">
          <div class="panel-heading EIN-hide-t EIN-hide">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#detailsAccordion" href="#details3" class="collapsed">Details<i class="fa fa-caret-down"></i><i class="fa fa-caret-up"></i></a>
            </h4>
          </div>
          <div id="details3" class="panel-collapse collapse">
            <div class="panel-body">
              <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>              
              <? if ($summary): ?>
                <h6 class="accordionSubheading">Summary</h6>
                <span class="accordionParagraph"><?=$summary?></span><br>
              <? endif; ?>
              <? if( isset($this->tabs['Reviews']) ): ?>
                <? $reviewSources = $this->tabs['Reviews']->getContent($this->driver->getCleanISBN()); ?>
                <? if( count($reviewSources) > 0 ): ?>
                  <h6 class="accordionSubheading accordionGap">Published Reviews</h6>
                  <? foreach( $reviewSources as $reviews ): ?>
                    <? foreach( $reviews as $review ): ?>
                      <span class="reviewSource"><?=$review['Source']?>: </span>
                      <span class="accordionParagraph">"<?=$review['Content']?>"</span><br>
                      <span class="EIN-col-m-12 reviewCopyright"><?=$review['Copyright']?></span><br>
                    <? endforeach; ?>
                  <? endforeach; ?>
                <? endif; ?>
              <? endif; ?>
              <h6 class="accordionSubheading accordionGap">Additional Information</h6>
              <table class="EIN-col-m-12 accordionTable">
                <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Publisher')?></td>
                    <td><? foreach($publications as $thisPublication): ?>
                      <span><?= $this->escapeHtml($thisPublication->getPlace()) . $this->escapeHtml($thisPublication->getName()) . $this->escapeHtml($thisPublication->getDate()) ?></span><br>
                    <? endforeach; ?></td>
                  </tr>
                <? endif; ?>
                <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Edition')?></td>
                    <td><?=$this->escapeHtml($edition)?></td>
                  </tr>
                <? endif; ?>
                <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Contributors')?></td>
                    <td>
                      <? foreach ($authors['secondary'] as $field): ?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><br><? endforeach; ?>
                    </td>
                  </tr>
                <? endif; ?>
                <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Language')?></td>
                    <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
                  </tr>
                <? endif; ?>
                <? /* $marcDesc = $this->driver->getFormattedMarcDetails(300,['|abc']); if (!empty($marcDesc)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('Description')?></td>
                    <td><?=$this->escapeHtml($marcDesc[0][0])?></td>
                  </tr>
                <? endif; */ ?>
                <? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
                  <tr>
                    <td class="colophonHeading"><?=$this->transEsc('ISBN')?></td>
                    <td><? foreach ($isbns as $isbn): ?><?= $this->escapeHtml($isbn)?><br/><? endforeach; ?></td>
                  </tr>
                <? endif; ?>
              </table>
            </div>
          </div>
        </div>
      </div>
      </div>
      <script type="text/javascript">
        $('.panel-heading a').on('click',function(e){
          // prevent them from dismissing the last open section if we're in tablet or desktop layout
          if($(document).width() >= 600) {
            if($($(this).attr("href")).hasClass('in')){
              e.stopPropagation();
            }
            // You can also add preventDefault to remove the anchor behavior that makes the page jump
            e.preventDefault();
          }
        });
        $('body').css({"overflow-y":"hidden"});
        if($(document).width() >= 600) {
          $('.panel-heading<?=($isOverDrive?".overdriveHeader":"")?> a').first().click();
        }
        $('body').css({"overflow-y":"auto"});
        $('#detailsAccordion').css({"min-height":$('.accordionButtonsLeft').height() + "px"});
      </script>
    </div>
  </div>
</div>
