<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $record = $this->record($this->driver);
?>
<div class="row result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?> EIN-col-m-12">
  <div class="EIN-col-m-1">
    <label class="pull-left flip"><?=$this->record($this->driver)->getCheckbox() ?></label>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($id)?>" class="hiddenId" />
    <input type="hidden" value="<?=$this->escapeHtmlAttr($source)?>" class="hiddenSource" />
  </div>
  <div class="EIN-col-m-3">
    <div class="text-center" style="padding:10px">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $largeThumb = $record->getThumbnail('large'); ?>
      <? if ($largeThumb): ?>
        <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($largeThumb);?>"/>
        </a>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>
    </div>
  </div>
  <div class="EIN-col-m-8" style="padding-right:10px">
    <div class="EIN-col-m-12 EIN-col-t-8 EIN-col-8">
      <h1 property="name" class="itemTitle"><a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->escapeHtml(($this->driver->getShortTitle() == "") ? trim($this->driver->getTitle(),"\0\t\n\x0B\r /") : (trim($this->driver->getShortTitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getSubtitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getTitleSection(),"\0\t\n\x0B\r /")))?></a></h1>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
        <h4 property="author" class="itemAuthor">by <a href="<?=$record->getLink('author', $authors['main'])?>" class="authorLink"><?=$this->escapeHtml($authors['main'])?></a></h4>
      <? endif; ?>

      <table>
        <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
          <? $firstTime = true; foreach( $formats as $thisFormat ): ?>
            <tr>
              <td class="EIN-hide-m itemDetailCategory"><?=($firstTime?"Format:":"&nbsp;")?></td>
              <td style="padding-bottom:5px">
                <span class="formatTag"><?=$thisFormat?></span>

                <? if( $firstTime ): ?>
                  <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                    <? foreach ($publications as $field): ?>
                      <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                        <span property="publicationDate" class="publishDate"><?=$this->escapeHtml($pubDate)?></span>
                      <? endif; ?>
                    <? endforeach; ?>
                  <? endif; ?>
                  <? $firstTime = false; ?>
                <? endif; ?>
              </td>
            </tr>
          <? endforeach; ?>
        <? endif; ?>

        <tr>
          <td class="EIN-hide-m itemDetailCategory">Availability:</td>
          <td style="padding-bottom:5px">
            <span class="status ajax-availability hidden"><i class="fa fa-spinner"></i>&nbsp<?=$this->transEsc('Loading')?>...</span>
          </td>
        </tr>
      </table>
    </div>
    <?
      if($user):
        $holdClick = "";
        $saveClick = " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown" . str_replace(".", "", $this->driver->getUniqueID()) . "\"";
      else:
        $holdClick = " onClick=\"Lightbox.get('MyResearch','Login')\"";
        $saveClick = " onClick=\"Lightbox.get('MyResearch','Login')\"";
      endif;
    ?>
    <div class="EIN-col-m-12 EIN-col-t-4 EIN-col-4" style="padding:5px 0px 10px">
      <div class="EIN-col-m-6 EIN-col-t-12 EIN-col-12">
        <button class="btn-default leftButton"<?=$holdClick?> disabled><i class="fa fa-spinner"></i>&nbsp;Loading...</button>
        <div class="EIN-col-m-12 dropdown" id="holdButtonDropdown<?=str_replace(".", "", $this->driver->getUniqueID())?>">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
          </ul>
        </div>
      </div>
      <? $hasOnList = false; 
         if($user):
           $myLists = $user->getLists(); 
           foreach($myLists as $list): 
             if($list->contains($this->driver->getResourceSource()."|".$this->driver->getUniqueID())):
               $hasOnList = true;
             endif;
           endforeach; 
         endif;
      ?>
      <div class="EIN-col-m-6 EIN-col-t-12 EIN-col-12">
        <button class="btn-default rightButton"<?=$saveClick?>><?=($hasOnList)?"Manage Lists":"Add to List"?><?=($user?"<i class=\"fa fa-caret-down\"></i>":"")?></button>
        <div class="EIN-col-m-12 dropdown" id="saveButtonDropdown<?=str_replace(".", "", $this->driver->getUniqueID())?>">
          <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            <? if($user):  foreach($myLists as $list): ?>
              <li>
                <? if($list->contains($this->driver->getResourceSource()."|".$this->driver->getUniqueID())): ?>
                  <form method="post" action="<?=$this->url('userList', array('id' => $list->id))?>">
                    <input type="hidden" name="confirm" value="1">
                    <input type="hidden" name="delete" value="<?=$this->driver->getUniqueID()?>">
                    <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                    <input type="hidden" name="list" value="<?=$list->id?>">
                    <button class="btn-dropdown btn-standardDropdown" onClick="$(this).parents('.dropdown').siblings('.rightButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')"><i class="fa fa-check greenCheck"></i><?=$list->title?></button>
                  </form>
                <? else: ?>
                  <form method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>">
                    <input type="hidden" name="submit" value="1">
                    <input type="hidden" name="id" value="<?=$this->driver->getUniqueID()?>">
                    <input type="hidden" name="source" value="<?=$this->driver->getResourceSource()?>">
                    <input type="hidden" name="list" value="<?=$list->id?>">
                    <button class="btn-dropdown btn-standardDropdown" onClick="$(this).parents('.dropdown').siblings('.rightButton').html('<i class=\'fa fa-spinner bwSpinner\'></i>&nbsp;Loading...')"><?=$list->title?></button>
                  </form>
                <? endif; ?>
              </li>
            <? endforeach;  endif; ?>
            <li><button class="btn-dropdown btn-standardDropdown" onclick="Lightbox.get('MyResearch','EditList',{'id':'NEW','recordId':'<?=$this->driver->getUniqueID()?>'})">New list...</button></li>
            <? if ($hasOnList): ?>
              <hr class="stretchHR">
              <li><span class="modalNote">Click a non-checked list to add this title.  Click a checked list to remove this title.</span></li>
            <? endif; ?>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
</div>
