<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
  $account = $this->auth()->getManager();
  $user = $account->isLoggedIn();
  $record = $this->record($this->driver);
  $urls = $this->driver->getURLs();
?>
<div class="row result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?> EIN-col-m-12">
  <div class="EIN-col-m-12"><hr style="margin:5px 0"></div>
  <table class="EIN-col-m-12"><tr>
    <td class="EIN-col-m-1" style="margin:auto">
      <span class="pull-left flip"><?=$record->getHoldCheckbox($this->driver->getResourceSource() . '|' . $id, ($list_id ? ("list_" . $list_id) : "")) ?></span>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($id)?>" class="hiddenId" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($source)?>" class="hiddenSource" />
      <input type="hidden" value="true" class="hiddenLoadThisStatus">
    </td>
    <td class="EIN-col-m-3" style="vertical-align:top">
      <div class="text-center" style="padding:10px">
        <? /* Display thumbnail if appropriate: */ ?>
        <? $largeThumb = $record->getThumbnail('large'); ?>
        <? if ($largeThumb): ?>
          <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
            <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($largeThumb);?>"/>
          </a>
        <? else: ?>
          <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <? endif; ?>
      </div>
    </td>
    <td class="EIN-col-m-8">
      <div class="highlightContainer EIN-col-m-12 EIN-col-t-8 EIN-col-8">
        <h1 property="name" class="itemTitle"><a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->escapeHtml(($this->driver->getShortTitle() == "") ? trim($this->driver->getTitle(),"\0\t\n\x0B\r /") : (trim($this->driver->getShortTitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getSubtitle(),"\0\t\n\x0B\r /") . ' ' . trim($this->driver->getTitleSection(),"\0\t\n\x0B\r /")))?></a></h1>

        <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
        <? if (isset($authors['main']) && !empty($authors['main'])): ?>
          <h4 property="author" class="itemAuthor">by <a href="<?=$record->getLink('author', $authors['main'])?>" class="authorLink"><?=$this->escapeHtml($authors['main'])?></a></h4>
        <? endif; ?>

        <table>
          <? $languages = $this->driver->getLanguages(); $showLanguages = false; ?>
          <? foreach( $languages as $thisLanguage ): ?>
              <? $showLanguages |= ($thisLanguage != "English"); ?>
          <? endforeach; ?>
          <? if ($showLanguages): ?>
            <? $languageCount = 0; $hash = md5($this->driver->getUniqueID()); foreach( $languages as $thisLanguage ): ?>
              <? if( $languageCount == 3 ): ?>
                <tr class="languageAccordionLess<?=$hash?>" style="display:table-row;font-size:14px">
                  <td class="EIN-hide-m itemDetailCategory">&nbsp;</td>
                  <td style="padding-bottom:5px"><a class="moreLink" onclick="ToggleLanguageAccordion('<?=$hash?>',1);">More</a></td>
                </tr>
              <? endif; ?>
              <tr<?=(($languageCount >= 3) ? (" class=\"languageAccordionMore" . $hash . "\" style=\"display:none\"") : "")?>>
                <? if ($languageCount == 0): ?>
                  <td rowspan=<?=((count($languages) <= 3)?count($languages):"3")?> class="EIN-hide-m itemDetailCategory"><?=("Language" . (($this->driver->getFormatCategory()=="Video")?" and/or Subtitles:":":"))?></td>
                <? elseif ($languageCount >= 3): ?>
                  <td class="EIN-hide-m itemDetailCategory">&nbsp</td>
                <? endif; ?>
                <td style="padding-bottom:5px">
                  <span class="languageTag"><?=$thisLanguage?></span>
                  <? $languageCount++; ?>
                </td>
              </tr>
            <? endforeach; ?>
            <? if( $languageCount > 3 ): ?>
              <tr class="languageAccordionMore<?=$hash?>" style="display:none;font-size:14px">
                <td class="EIN-hide-m itemDetailCategory">&nbsp;</td>
                <td><a class="moreLink" onclick="ToggleLanguageAccordion('<?=$hash?>',0);">Less</a></td>
              </tr>
              <script type="text/javascript">
                function ToggleLanguageAccordion(hashCode,showMore) {
                  $('.languageAccordionMore' + hashCode).css({"display":(showMore ? "table-row" : "none")});
                  $('.languageAccordionLess' + hashCode).css({"display":(showMore ? "none" : "table-row")});
                  moveButtons();
                }
              </script>
            <? endif; ?>
          <? endif; ?>

          <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
            <? $firstTime = true; foreach( $formats as $thisFormat ): ?>
              <tr>
                <td class="EIN-hide-m itemDetailCategory"><?=($firstTime?"Format:":"&nbsp;")?></td>
                <td style="padding-bottom:5px">
                  <span class="formatTag"><?=$thisFormat?></span>

                  <? if( $firstTime ): ?>
                    <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
                      <? foreach ($publications as $field): ?>
                        <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                          <span property="publicationDate" class="publishDate"><?=$this->escapeHtml($pubDate)?></span>
                        <? break; endif; ?>
                      <? endforeach; ?>
                    <? endif; ?>
                    <? $firstTime = false; ?>
                  <? endif; ?>
                </td>
              </tr>
            <? endforeach; ?>
          <? endif; ?>
          <tr>
            <td class="EIN-hide-m itemDetailCategory">Availability:</td>
            <td style="padding-bottom:5px">
              <span class="status ajax-availability hidden"><i class="fa fa-spinner"></i>&nbsp<?=$this->transEsc('Loading')?>...</span>
            </td>
          </tr>
          <? if( !empty($urls) ): ?>
            <tr>
              <td class="EIN-hide-m itemDetailCategory hidden">Links:</td>
              <td><span class="accordionParagraph">
                <? foreach($urls as $thisURL): ?>
                  <div class="itemURL hidden"><a href="<?=$thisURL["url"]?>" target="_blank"><?=((strpos($thisURL["url"], "http://carnegielbyofpittpa.oneclickdigital.com") !== false) ? 'Download from OneClick' : $thisURL["desc"])?></a>
                    <? if( $count == 2 && count($urls) > 3 ): ?>
                      <br><a href="<?=$this->recordLink()->getUrl($this->driver)?>">Plus <?=(count($urls) - 3)?> more ...</a>
                      </div>
                      <? break; ?>
                    <? endif; ?>
                  </div>
                <? endforeach; ?>
              </td>
            </tr>
          <? endif; ?>
        </table>
      </div>
      <?
        if($user):
          $myLists = $user->getLists();
          $hasLists = $user->getLists($this->driver->getResourceSource()."|".$this->driver->getUniqueID());
          $containingLists = [];
          foreach($hasLists as $thisList):
            $containingLists[] = $thisList->list_id;
          endforeach;

          $itemData = json_encode(["id" => $this->driver->getResourceSource() . "|" . $this->driver->getUniqueID(), "lists" => $containingLists, "saveLink" => $this->recordLink()->getActionUrl($this->driver, 'Save')]);
          $itemData = str_replace("\"", "\\'", $itemData);

          $holdClick = "";
          $saveClick = " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown\" onclick=\"moveSaveDropdown(this, '" . $itemData . "');\"";
          $mobileSaveClick = " data-toggle=\"dropdown\" data-target=\"#saveButtonDropdown\" onclick=\"moveSaveDropdown($(this).parent().next().children('span'), '" . $itemData . "');\"";
        else:
          $holdClick = " onClick=\"Lightbox.get('MyResearch','Login',false,{'clearLightbox':true})\"";
          $saveClick = " onClick=\"Lightbox.get('MyResearch','Login',false,{'clearLightbox':true})\"";
          $mobileSaveClick = " onClick=\"Lightbox.get('MyResearch','Login',false,{'clearLightbox':true})\"";
        endif;
      ?>
      <div class="EIN-hide-m EIN-col-t-4 EIN-col-4" style="padding:5px 0px 10px">
        <div class="EIN-col-m-12">
          <button class="btn-default leftButton"<?=$holdClick?> disabled><i class="fa fa-spinner"></i>&nbsp;Loading...</button>
          <div class="dropdown EIN-hide-m" id="holdButtonDropdown<?=str_replace(".", "", $this->driver->getUniqueID())?>">
            <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            </ul>
          </div>
        </div>
        <div class="EIN-col-m-12">
          <button class="btn-default rightButton"<?=$saveClick?>><?=$this->transEsc("list_manage")?><?=($user?"<i class=\"fa fa-caret-down\"></i>":"")?></button>
        </div>
      </div>
    </td>
  </tr><tr>
    <td class="EIN-col-m-12 EIN-hide-t EIN-hide" colspan=3>
      <div class="EIN-col-m-12" style="padding:5px 0px 10px">
        <div class="EIN-col-m-6">
          <button class="btn-default leftButton"<?=$holdClick?> disabled><i class="fa fa-spinner"></i>&nbsp;Loading...</button>
          <div class="dropdown EIN-hide-m" id="holdButtonDropdownMobile<?=str_replace(".", "", $this->driver->getUniqueID())?>">
            <ul role="navigation" class="dropdown-menu standardDropdown manageListDropdown">
            </ul>
          </div>
        </div>
        <div class="EIN-col-m-6">
          <button class="btn-default rightButton"<?=$mobileSaveClick?>><?=$this->transEsc("list_manage")?><?=($user?"<i class=\"fa fa-caret-down\"></i>":"")?></button>
        </div>
        <div class="EIN-col-m-12">
          <span></span>
        </div>
      </div>
    </td>
  </tr></table>
</div>
