<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

      // Deal with cart stuff:
      if (!isset($this->renderingError)) {
        $cart = $this->cart();
        $this->jsTranslations()->addStrings(
          array(
            'bulk_email_success' => 'bulk_email_success',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'loading' => 'Loading',
            'sms_success' => 'sms_success'
          )
        );
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          $this->headScript()->appendScript(
            'var cartCookieDomain = ' . (!empty($domain) ? "'$domain'" : 'false') . ';'
          );
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmDelete' => 'confirm_delete',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
              'no_tags' => 'No Tags'
            )
          );
        }
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }
    ?>
    <?=$this->headScript()?>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
    <link href="/themes/truefit/css/einetwork.css" media="all" rel="stylesheet" type="text/css">
    <script src="/themes/truefit/js/hmac-sha256.js"></script>
    <script src="/themes/truefit/js/enc-base64-min.js"></script>
    <script src="/themes/truefit/js/backgroundLoader.js"></script>
  </head>
  <body>
    <!-- *google analytics* -->
    <div>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-80683816-1', 'auto');
        ga('send', 'pageview');

      </script>
    </div>
    <iframe id="loginFrame" name="loginFrame" style="display:none"></iframe>
    <? // see whether or not we need to do some background loading of holds/checkouts
      $account = $this->auth()->getManager();
      if( $user = $account->isLoggedIn() ):
        if( $this->ils()->getDriver()->getSessionVar('holds') === null || $this->ils()->getDriver()->getSessionVar('staleHoldsHash') !== null ):
    ?>
      <iframe style="display:none" id="backgroundLoaderHolds"></iframe>
    <?
        endif;
        if( $this->ils()->getDriver()->getSessionVar('checkouts') === null || $this->ils()->getDriver()->getSessionVar('staleCheckoutsHash') !== null ):
    ?>
      <iframe style="display:none" id="backgroundLoaderCheckouts"></iframe>
    <?
        endif;
      endif;
    ?>
    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <header role="banner" class="hidden-print">
      <div class="container navbar">
        <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
        <?=$this->render('header.phtml')?>
      </div>
    </header>
    <div role="main" class="main template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?>">
      <div class="container">
        <div class="EIN-col-m-12" style="height:10px"></div>
        <?=$this->layout()->content ?>
      </div>
      <span id="returnToTop" class="returnToTop" onclick="$(window).scrollTop(0)"><i class="fa fa-long-arrow-up"></i></span>
      <script type="text/javascript">
        var returnOffset = 150;
        var mostRecentSearchBtn = null;

        jQuery(document).ready(function() {
          moveButtons();
          $(window).scroll(moveButtons);
          $(window).resize(moveButtons);
        });

        function moveButtons() {
          // return to top
          $('#returnToTop').css("margin-left", (($('#pageFooter').width() / 2) - 50) + "px");
          if( document.body.clientHeight < $(this).height() * 2) {
            $('#returnToTop').css("bottom", (0 - returnOffset) + "px");
          } else if($(this).scrollTop() < returnOffset) {
            $('#returnToTop').css("bottom", ($(this).scrollTop() - returnOffset) + "px");
          } else if($(this).scrollTop() > (document.body.clientHeight - $(this).height() - $('#pageFooter').height() + 20))  {
            $('#returnToTop').css("bottom", ($(this).scrollTop() - document.body.clientHeight + $(this).height() + $('#pageFooter').height() - 20) + "px");
          } else  {
            $('#returnToTop').css("bottom", "0px");
          }

          // search dropdown
          if( mostRecentSearchBtn != null ) {
            var newLeft = $(mostRecentSearchBtn).offset().left + $(mostRecentSearchBtn).width() - $('#searchBoxDropdown').children("ul").width();
            var newTop = $(mostRecentSearchBtn).offset().top + $(mostRecentSearchBtn).height();
            $('#searchBoxDropdown').offset({left:newLeft, top:newTop});
            $('#searchBoxDropdown').css('width', $('#searchBoxDropdown').children("ul").outerWidth());
          }
        }
      </script>
    </div>
    <footer role="contentinfo" class="hidden-print">
      <div id="pageFooter" class="container" style="padding-top:0px;border-top:none">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy ?>
      </div>
    </footer>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-noBorderAlternate close" id="modalClose" data-dismiss="modal" aria-hidden="true"><i class="fa fa-close"></i></button>
            <h4 id="modalTitle" class="modal-title"></h4>
          </div>
          <div style="position:relative">
            <div class="modal-body" style="color:#3d3d3d">
              <span><i class="fa fa-spinner"></i></span>
              <span>&nbsp;<?=$this->transEsc('Loading') ?>...</span>
            </div>
            <div class="modalScrollBar" onmousedown="StartScrollBarDrag(false); return false;" ontouchstart="StartScrollBarDrag(true); return false;"><div class="modalScrollSlider"></div><div class="modalScrollExpandedClickZone"></div></div>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
    <script type="text/javascript">
      Lightbox.addOpenAction(sizeModal);
      $(window).resize(sizeModal);
      var initialOffset = -1;
      var maxRange = -1;
      var scrollLogic = function(e) {
        var pageY = initialOffset;
        if( e.hasOwnProperty("pageY") ) {
          pageY = e.pageY;
        } else if( e.originalEvent.touches.length == 1 ) {
          pageY = e.originalEvent.touches[0].pageY;
        } else {
          return;
        }
        if( initialOffset == -1 ) {
          initialOffset = $('.modalScrollSlider').offset().top - $('.modalScrollBar').offset().top - pageY;
        }
        var target = pageY + initialOffset;
        if( target < 0 ) {
          target = 0;
        } else if( target > ($('.modalScrollBar').height() - $('.modalScrollSlider').height()) ) {
          target = $('.modalScrollBar').height() - $('.modalScrollSlider').height();
        }
        var factor = target / ($('.modalScrollBar').height() - $('.modalScrollSlider').height());
        $('.modalScrollSlider').css({"top":(target + "px")});
        $('.modal-body').scrollTop(factor * maxRange);
      };
      var mouseUpLogic = function(e) {
        $(document).unbind("mousemove touchmove", scrollLogic);  
        $(document).unbind("mouseup touchend", mouseUpLogic); 
        initialOffset = -1; 
      };
      function StartScrollBarDrag(isMobile) {
        $(document).bind(isMobile ? "touchmove" : "mousemove", scrollLogic);
        $(document).bind(isMobile ? "touchend" : "mouseup", mouseUpLogic);
      }
      function sizeModal() {
        setTimeout( function() {
          var targetPos = $('.modal-body').scrollTop();
          $('.modal-body').css("max-height","none");
          var offset = parseInt($('.modal-dialog').css('margin-top').replace('px', '')) + 
                       parseInt($('.modal-dialog').css('margin-bottom').replace('px', '')) + 
                       parseInt($('.modal-dialog').css('border-top-width').replace('px', '')) + 
                       parseInt($('.modal-dialog').css('border-bottom-width').replace('px', '')) + 
                       $('.modal-header').outerHeight() + $('.modal-footer').outerHeight();
          var max = $(window).height() - offset;
          var barHeight = max - 30;
          var sliderHeight = barHeight * barHeight / $('.modal-body').outerHeight();
          var hidden = (max > $('.modal-body').outerHeight());
          maxRange = $('.modal-body').outerHeight() - max;
          $('.modal-body').css({"max-height":(max + "px"),"overflow-y":"hidden"});
          $('.modalScrollBar').css({"height":(barHeight + "px"),"display":(hidden ? "none" : "block")});
          $('.modalScrollSlider').css({"height":(sliderHeight + "px")});
          Lightbox.addCloseAction(function() {
            $('.modal-footer').html("");
            $('.modalScrollBar').css({"height":"0px","display":"none"});
            $('.modalScrollSlider').css({"height":"0px", "top":"0px"});
            $('.modal-body').css({"max-height":"none","overflow-y":"auto"});
            $('.modal-body').scrollTop(0);
            initialOffset = -1;
            maxRange = -1;
          } );
          $('.modal-body').scrollTop(targetPos);
          $('.modalScrollSlider').css({"top":((targetPos * (barHeight - sliderHeight) / maxRange) + "px")});
        }, 20);
      }
      
    </script>
  </body>
</html>
