<? if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->id)?>" />
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->title)?>" />
<? endif; ?>
<? $user = $this->auth()->isLoggedIn(); ?>
<div class="checkbox">
  <label>
    <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
    <?=$this->transEsc('select_page')?> | <?=$this->transEsc('with_selected')?>:
  </label>
</div>
<div class="btn-group">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <? if ($list->isBookCart()): ?>
      <input id="ribbon-save" class="btn btn-default modal-link" type="submit" name="saveList" title="<?=$this->transEsc('bookbag_save_selected')?>" value="<?=$this->transEsc('Add to List')?>"/>
    <? else: ?>
      <input type="submit" class="btn btn-default" name="add" value="<?=$this->transEsc('Add to Book Cart')?>"/>
    <? endif; ?>
  <? endif; ?>
</div>