<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VuFindAdmin\Controller\TagsController'           => __DIR__ . '/src/VuFindAdmin/Controller/TagsController.php',
    'VuFindAdmin\Controller\MaintenanceController'    => __DIR__ . '/src/VuFindAdmin/Controller/MaintenanceController.php',
    'VuFindAdmin\Controller\ConfigController'         => __DIR__ . '/src/VuFindAdmin/Controller/ConfigController.php',
    'VuFindAdmin\Controller\SocialstatsController'    => __DIR__ . '/src/VuFindAdmin/Controller/SocialstatsController.php',
    'VuFindAdmin\Controller\StatisticsController'     => __DIR__ . '/src/VuFindAdmin/Controller/StatisticsController.php',
    'VuFindAdmin\Controller\AbstractAdmin'            => __DIR__ . '/src/VuFindAdmin/Controller/AbstractAdmin.php',
    'VuFindAdmin\Controller\AdminController'          => __DIR__ . '/src/VuFindAdmin/Controller/AdminController.php',
    'VuFindAdmin\Module'                              => __DIR__ . '/Module.php',
    'VuFindTest\Controller\SocialstatsControllerTest' => __DIR__ . '/tests/unit-tests/src/VuFindTest/Controller/SocialstatsControllerTest.php',
);
