<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'VuFindConsole\Controller\GenerateController' => __DIR__ . '/src/VuFindConsole/Controller/GenerateController.php',
    'VuFindConsole\Controller\UtilController'     => __DIR__ . '/src/VuFindConsole/Controller/UtilController.php',
    'VuFindConsole\Controller\AbstractBase'       => __DIR__ . '/src/VuFindConsole/Controller/AbstractBase.php',
    'VuFindConsole\Controller\LanguageController' => __DIR__ . '/src/VuFindConsole/Controller/LanguageController.php',
    'VuFindConsole\Controller\HarvestController'  => __DIR__ . '/src/VuFindConsole/Controller/HarvestController.php',
    'VuFindConsole\Controller\ImportController'   => __DIR__ . '/src/VuFindConsole/Controller/ImportController.php',
    'VuFindConsole\Mvc\Router\ConsoleRouter'      => __DIR__ . '/src/VuFindConsole/Mvc/Router/ConsoleRouter.php',
    'VuFindConsole\Module'                        => __DIR__ . '/Module.php',
    'VuFindTest\Mvc\Router\ConsoleRouterTest'     => __DIR__ . '/tests/unit-tests/src/VuFindTest/Mvc/Router/ConsoleRouterTest.php',
);
